### ISSUE TITLE
Voter nodes don't vote on ChainHeadEvent (New Block)

### ISSUE THREAD

**Issue by magooster** [jpmorganchase/quorum-examples#10]
A node will only vote on a ChainHeadEvent if the node is synced with the chain. In the 7 node example the nodes do not set there sync status to true as they do not ever undertake a chain download.

The maker node has the --singleblockmaker flag set so its synced flag is set to true. 

The chain progresses because the maker node votes twice and the voting nodes vote when their deadline timer expires and a CreateBlock event occurs.

Expected behaviour can be achieved by setting the --singleblockmaker flag to all nodes.

**Comment by patrickmn** [comment]
Is this still an issue? I know there were similar issues in the main Quorum repository.

If it is, do you mind re-submitting this as an issue in https://github.com/jpmorganchase/quorum/issues ?
