### ISSUE TITLE
--mine required?

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [jpmorganchase/quorum-examples#101]
I just looked at line https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/istanbul-start.sh#L11

Is ```--mine``` required for IBFT to work?

**Comment by fixanoid** [comment]
Mine is required for istanbul. Please see docs here: https://github.com/ethereum/EIPs/issues/650

**Comment by Kl4rity** [comment]
Hi there, 

I am working on setting up quorum nodes with Istanbul and, unfortunately, they seem to neither recognise the --syncmode 'full' nor the --mine or --minerthreads 1 arguments. It does accept all other arguments such as --datadir, --rpc etc...

Everything is based on the https://github.com/jpmorganchase/quorum.git repo (geth version etc.)

The full command I am trying to execute is the
geth --datadir /qdata/dd --mine --minerthreads 1 --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --nodiscover --unlock 0 --password /qdata/passwords.txt

The log message I then get is:
"flag provided but not defined: -mine"

This only depends on which command of these 3 --mine --minerthreads 1 --syncmode full is first in the above command.

(Constellation Node starts fine.)

Any idea why this happens? I've been playing around with this for some time now and can't get it to recognise the flags. Thank you!
