### ISSUE TITLE
tx pending

### ISSUE THREAD

**Issue by ghost** [jpmorganchase/quorum-examples#103]
`
> eth.sendTransaction({from:eth.coinbase,to:eth.coinbase,value:1,gasPrice:0})
"0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11"
> eth.getTransaction('0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11')
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gas: 90000,
  gasPrice: 0,
  hash: "0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11",
  input: "0x",
  nonce: 298,
  r: "0xfaec83bbe9d5d4474f3c89b09770df8d08e041dc93a2af6f4bba7e8d94b7b569",
  s: "0x7837e6c17b061e3b52a0e01f03ec138f472e032571ccec568f272720bedcda34",
  to: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  transactionIndex: 0,
  v: "0x1c",
  value: 1
}
`

**Comment by jpmsam** [comment]
Works for me, please provide more details 

> eth.sendTransaction({from:eth.coinbase,to:eth.coinbase,value:1,gasPrice:0})
"0x41e9d30c620b545f65d6754d98fd8f0f441b169e9db04106403b698376312040"

>eth.getTransaction("0x41e9d30c620b545f65d6754d98fd8f0f441b169e9db04106403b698376312040")
{
  blockHash: "0x55df7456122698445f5e1c41f5512c994b34290b458c4ee69b396fbf8c8431bc",
  blockNumber: 14,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gas: 90000,
  gasPrice: 0,
  hash: "0x41e9d30c620b545f65d6754d98fd8f0f441b169e9db04106403b698376312040",
  input: "0x",
  nonce: 10,
  r: "0x97626b7a450e960384edb547a968eb0338479a6a6df911234c3954e7d77993b1",
  s: "0x575c90c375a625ab0b00f1dccab1d2dea8005d2455a5dcbed8f17b35feb7e903",
  to: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  transactionIndex: 0,
  v: "0x1b",
  value: 1
}

**Comment by sumitpatel93** [comment]
Still this issue persists I guess
{
    "Body": {
        "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "blockNumber": null,
        "from": "0x93c08172572c71F1b9B4699488d9a0604689D52b",
        "gas": 2000000,
        "gasPrice": "0",
        "hash": "0x586543c9b895908bb8a33effe448bcbe32bfb9ac2cf1ddaa75111183d1f8a8ff",
        "input": "0xfface7e0000000000000000000000000ed9d02e382b34818e88b88a309c7fe71e65f419d70756e6500000000000000000000000000000000000000000000000000000000",
        "nonce": 4,
        "to": "0x9d13C6D3aFE1721BEef56B55D303B09E021E27ab",
        "transactionIndex": 0,
        "value": "0",
        "v": "0x26",
        "r": "0x437358093693134a31a2bff87c8402845673fafc1613289952ad987d46e597d8",
        "s": "0x470e92dfd79814cc37841962606c351878c93754c794df23b9dbb0e34b42f2"
    }
}
