### ISSUE TITLE
Failed to run 7nodes at geth execution

### ISSUE THREAD

**Issue by aroommen** [jpmorganchase/quorum-examples#104]
I am running the 7nodes examples with the vagrant setup and the run is stopping with the ./raft-init.sh execution itself. The run terminates with the following message

$ ./raft-init.sh
[] Cleaning up temporary data directories
[] Configuring node 1 (permissioned)
INFO [06-15|07:14:43] Allocated cache and file handles database=/vagrant/examples/7nodes/qdata/dd1/geth/chaindata cache=16 handles=16
Fatal: Failed to open database: sync /vagrant/examples/7nodes/qdata/dd1/geth/chaindata: invalid argument
I also found a lock in the data directory
$ ls qdata/dd1/geth/chaindata/
CURRENT LOCK LOG

I had made some progress by moving the qdata ( data directory ) from the vagrant shared directory to the VM home directory (/home/vagrant/qdata) but even with that I eventually ran into an IPC socket file issue. So I stopped with that direction as well.

System information
Geth version: geth version
Geth
Version: 1.7.2-stable
Git Commit: df4267a
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Linux ubuntu-xenial 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Branch, Commit Hash or Release: git status

On branch master
Your branch is up-to-date with 'origin/master'.

Expected behaviour
The initialization proceeds smoothly

Actual behaviour
$ ./raft-init.sh
[] Cleaning up temporary data directories
[] Configuring node 1 (permissioned)
INFO [06-15|07:14:43] Allocated cache and file handles database=/vagrant/examples/7nodes/qdata/dd1/geth/chaindata cache=16 handles=16
Fatal: Failed to open database: sync /vagrant/examples/7nodes/qdata/dd1/geth/chaindata: invalid argument

Steps to reproduce the behaviour
% git clone https://github.com/jpmorganchase/quorum-examples
% cd quorum-examples
% vagrant up
% vagrant ssh
% cd /vagrant/examples/7nodes/
% raft-init.sh

Backtrace
[] Cleaning up temporary data directories
[] Configuring node 1 (permissioned)
INFO [06-15|07:14:43] Allocated cache and file handles database=/vagrant/examples/7nodes/qdata/dd1/geth/chaindata cache=16 handles=16
Fatal: Failed to open database: sync /vagrant/examples/7nodes/qdata/dd1/geth/chaindata: invalid argument

**Comment by fixanoid** [comment]
Hi @aroommen please make sure you are executing it in the vagrant environment. From your exmaple above, it looks like you are running it in your host os.

**Comment by aroommen** [comment]
@fixanoid Thanks for the response. I was actually running this on vagrant environment although I have not included that as part of the run steps. Since then I have been able to get this to run by doing manual installation of each of the pieces as listed in the vagrant/bootstrap.sh file and increasing the memory limit to about 4gb ( actual consumption is less than 3gb) in the VM. 
I think something might be off with this part of the bootstrap.sh
Line 41
chown -R vagrant:vagrant /home/vagrant/quorum /home/vagrant/quorum-examples
or could it be just a memory limit issue.

**Comment by sherrygarg** [comment]
even i'm getting this same issue..
vagrant@ubuntu-xenial:~/quorum-examples/examples/7nodes$ sudo ./raft-init.sh
[*] Cleaning up temporary data directories
[*] Configuring node 1 (permissioned)
./raft-init.sh: line 15: geth: command not found

need help..

**Comment by prd-fox** [comment]
@sherrygarg this looks to be a different problem. Can you please open a new GitHub issue for this?
