### ISSUE TITLE
Geth version used is not master [ Selective private transaction issue ]

### ISSUE THREAD

**Issue by Himanshu-Pandey** [jpmorganchase/quorum-examples#105]
When a contract is privately deployed between nodes and a private transaction is generated in between a subset of these nodes, then the left out notes crashes due to issue in there constellation.

This is fixed in using Geth Master.

**Comment by fixanoid** [comment]
Hey @Himanshu-Pandey this will be closed after we pull in and release geth 1.8.8 changes,

**Comment by fixanoid** [comment]
We've updated the version that examples is pulling from.
