### ISSUE TITLE
Quorum/Raft  7nodes ether funding error

### ISSUE THREAD

**Issue by horca17** [jpmorganchase/quorum-examples#106]
Unable to send Ether from a funded (by genesis.json) account to another without Ether. The transaction is done without errors and provides a Tx number, but the balance keeps the same.

Node1
> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
1000000000
> eth.coinbase
"0xed9d02e382b34818e88b88a309c7fe71e65f419d"
> eth.sendTransaction({'from':eth.coinbase, 'to':'0xa9e871f88cbeb870d32d88e4221dcfbd36dd635a', 'value':web3.toWei(33, 'ether')})
"0x8362889114b97090d097bf79f168f0dd50617d29afc5cb69876ea15e19251113"
> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
1000000000

Node7
> eth.coinbase
"0xa9e871f88cbeb870d32d88e4221dcfbd36dd635a"
> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
0

I tried deploying contracts and doing privateFor: deployments and everything works fine, but why I am not able to interact with Ether?

Thanks.

**Comment by fixanoid** [comment]
@horca17 are you using unmodified Quorum? Could you please retest with master.

**Comment by horca17** [comment]
Hello, and thank you for your response.

Yes, I am using Master, this is the version:

MacBook-Pro-3:7nodes horaciocaceres$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 87d7c906e9eba93b618651ab5a427746506e2f30
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.10/libexec

This is the Transaction:

> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
1000000000
> eth.sendTransaction({'from':eth.coinbase,
'to':'0xa9e871f88cbeb870d32d88e4221dcfbd36dd635a', 'value':web3.toWei(33,
'ether')})
"0x8362889114b97090d097bf79f168f0dd50617d29afc5cb69876ea15e19251113"
>
eth.getTransactionReceipt("0x8362889114b97090d097bf79f168f0dd50617d29afc5cb69876ea15e19251113")
{
  blockHash:
"0x643e10edb72eb5d48436c1ea6713e336831e5198a3adc04fafaad04876ba2c6e",
  blockNumber: 1,
  contractAddress: null,
  cumulativeGasUsed: 0,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gasUsed: 0,
  logs: [],
  logsBloom:
"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  status: "0x1",
  to: "0xa9e871f88cbeb870d32d88e4221dcfbd36dd635a",
  transactionHash:
"0x8362889114b97090d097bf79f168f0dd50617d29afc5cb69876ea15e19251113",
  transactionIndex: 0
}

But if I send ether without a to: address, as to a contract

>eth.sendTransaction({'from':eth.coinbase, 'value':web3.toWei(33, 'ether')})
"0x30e809386935e75d87798c97bdc00e5c449e5a37b5fe8206f6e2e35e8104687b"
> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
999999967
>
eth.TransactionReceipt("0x30e809386935e75d87798c97bdc00e5c449e5a37b5fe8206f6e2e35e8104687b")
{
  blockHash:
"0xaa73dce56e14507c2d89cd76433fe6d2a17662df8f68a111c8ba399c07c5d567",
  blockNumber: 2,
  contractAddress: "0x1349f3e1b8d71effb47b840594ff27da7e603d17",
  cumulativeGasUsed: 21000,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gasUsed: 21000,
  logs: [],
  logsBloom:
"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  status: "0x1",
  to: null,
  transactionHash:
"0x30e809386935e75d87798c97bdc00e5c449e5a37b5fe8206f6e2e35e8104687b",
  transactionIndex: 0
}
>web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
999999967

Any idea?

Thanks.

Horacio

**Comment by horca17** [comment]
But if I use 2.0.1:

MacBook-Pro-3:~ horaciocaceres$ geth version
Geth
Version: 1.7.2-stable
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.9.7
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go


> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
1000000000

> eth.sendTransaction({'from':eth.coinbase,
'to':'0x46f50ca5623c968da2926a6b9ddfaa123fb4faf9', 'value':web3.toWei(33,
'ether')})
"0x930269f21ed27de14f0276abb758c812ba954638f4e3013e42b0728fab49f670"

> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
999999967


instance: Geth/v1.7.2-stable/darwin-amd64/go1.9.7
coinbase: 0x46f50ca5623c968da2926a6b9ddfaa123fb4faf9
at block: 29 (Fri, 07 May 48532496060 12:13:03 ART)
 datadir: /Users/horaciocaceres/5nodes/nodo2/qdata
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0
raft:1.0 rpc:1.0 txpool:1.0 web3:1.0

> web3.fromWei(eth.getBalance(eth.coinbase), 'ether')
1000000033

**Comment by fixanoid** [comment]
@horca17 is the account in the to field a smart contract? The value txns in private mode are not allowed.

**Comment by fixanoid** [comment]
@horca17 please pull master and re-test. Some notes:
- no value transfer is allowed in private txns
- you must define smart contract as payable to be able to transfer value

**Comment by horca17** [comment]
Hey,

I just signed the petition "Argentinos: Todos vayamos a votar el 27 de
Octubre, seamos más del 85% del padrón electoral argentino." and wanted to
see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/X6H7R4Sc2m

Thanks!
Horacio
