### ISSUE TITLE
genesis.json typo

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [jpmorganchase/quorum-examples#108]
I noticed a typo (it is ```mixHash``` in istanbul-genesis.json). I'm not sure though which is correct. Since istanbul-tools generate ```mixHash```, I assume it is correct this way.

https://github.com/jpmorganchase/quorum-examples/blob/fe500887e81ae94322727832157ce7f957ce36a8/examples/7nodes/genesis.json#L32

https://github.com/jpmorganchase/quorum-examples/blob/fe500887e81ae94322727832157ce7f957ce36a8/examples/7nodes/istanbul-genesis.json#L52

**Comment by fixanoid** [comment]
These are used for different configurations. The lower one is part of the IBFT 7node example priming and its correct. The upper one is Raft config.
