### ISSUE TITLE
The private tx succeed, but the balance does not change

### ISSUE THREAD

**Issue by zhj4655** [jpmorganchase/quorum-examples#109]
I run the raft-init.sh and raft-start.sh, and send a private tx from node1 to node2, the block was mined and the tx was recorded in the block, but when I run eth.getBalance(account1), the balance of the node1 didn`t change. I don`t know why?
The transaction:
`> eth.getTransaction("0x6d4b2b801d1d27798a0709510a1212e946ea340201014999b4d6d7dd9596a318")
{
  blockHash: "0xfe27c0efa2959c76503a29829cccaf45476571422fa5641128e0ba7d8fcdeccd",
  blockNumber: 1,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gas: 90000,
  gasPrice: 0,
  hash: "0x6d4b2b801d1d27798a0709510a1212e946ea340201014999b4d6d7dd9596a318",
  input: "0xb82e61b1f4e26bac8c1066d1d6eed7ff766fcc7959f4f554fd0cee59165f9d8e690462ad710ca29365a81d6e09405a85c7a99fab2cfe1a768833413c60dbf0ae",
  nonce: 0,
  r: "0x3bb11a206e1b3cf5a62ddec86f78d252cc5f448424430316a2ea1cb5063b7a63",
  s: "0x335c66ef6e10d6b5743c218712049913017ed90156e4ee043d456269f915da74",
  to: "0xca843569e3427144cead5e4d5999a3d0ccf92b8e",
  transactionIndex: 0,
  v: "0x25",
  value: 10000
}
`
when I send a public tx, it suceeded and the balance of the node1 changed.
I need help, thank you.

**Comment by jpmsam** [comment]
Private value transfer transactions aren't supported at this time.
