### ISSUE TITLE
./raft-start.sh doesn't start geth 

### ISSUE THREAD

**Issue by vkhymenko** [jpmorganchase/quorum-examples#110]
**What I do:**
1. git clone 7nodes example
2. cd 7nodes/
3. `./raft-init.sh`
4.`./raft-start.sh`

**Problem:**
Geth nodes do not start up after executing `./raft-start.sh`

**Expected behavior:**
After `./raft-start.sh` I want to `truffle migrate` my compiled contract to a node, but I get an error which says that there is no geth client running

I am using Ubuntu 16.04 LTS

Here is my truffle.js:
`module.exports = {
        networks: {
                development: {
                        host: "localhost",
                        port: 22000,
                        network_id: "*",
                        gasPrice: 0,
                        gas: 4500000
                },
                nodefour: {
                        host: "localhost",
                        port: 22003,
                        network_id: "*",
                        gasPrice: 0,
                        gas: 4500000
                },
                nodeseven: {
                        host: "localhost",
                        port: 22006,
                        network_id: "*",
                        gasPrice: 0,
                        gas: 4500000
                }
        }
};
`

Here is log from constellation1.log:
`14:40:25 [INFO] Log level is LevelWarn
14:40:25 [WARN] tm.key is too accessible. Please run: chmod 0600 tm.key
14:40:26 [WARN] No TLS certificate or key found; generating tls-client-cert.pem/tls-client-key.pem
14:40:33 [WARN] No TLS certificate or key found; generating tls-server-cert.pem/tls-server-key.pem
14:40:38 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "66:BD:9B:01:5F:E1:4F:20:10:FD:07:92:80:A3:CF:12:FA:12:F3:9D:D9:66:4B:5F:A8:6A:E0:41:9A:D4:7C:1A:C4:25:DB:52:2D:EA:44:36:F4:D1:13:A8:5A:00:92:AE:38:5F:CA:D3:67:F6:FF:68:03:5C:5C:61:49:30:FB:CC" for host 127.0.0.4
14:40:38 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "DA:4C:D5:9E:B2:64:87:92:7A:47:67:38:06:A2:77:C9:64:E2:F9:04:29:30:09:D7:AC:F6:9A:BF:2B:E8:4B:81:5D:D4:56:89:DF:22:23:55:BC:43:C2:26:90:93:2F:15:3D:DC:E4:6A:8B:B9:42:72:6F:CE:FC:2E:FD:32:B5:30" for host 127.0.0.6
14:40:38 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "69:E6:43:60:12:C0:4C:AB:56:9A:2D:F8:3E:88:28:7E:27:79:49:4D:E8:CC:04:62:B6:9A:FA:E6:22:EA:2E:E8:C8:BF:CF:09:55:9F:F8:A6:86:E7:BB:0A:49:47:69:D0:BA:A1:7B:97:73:70:CB:4A:3E:96:6F:B9:AC:B2:B8:18" for host 127.0.0.6
14:40:39 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "20:53:67:24:19:DC:33:8C:CB:DE:41:17:6D:AA:8F:99:B4:2A:5B:1F:1A:14:99:7D:7E:65:75:E0:38:E0:82:73:50:A9:19:95:28:A8:EC:27:32:85:9B:B6:43:19:CB:2F:59:6D:F5:E6:7D:A5:D1:BC:C0:C7:A7:51:38:5D:BF:03" for host 127.0.0.4
14:40:41 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "DD:8E:E6:2B:F2:34:A9:3A:96:99:1D:5E:14:77:17:A4:D1:DB:ED:18:37:33:92:AD:0E:7A:90:5D:5D:E0:63:8B:0F:89:CD:CC:B4:0F:50:44:69:9A:0B:E1:2B:5D:84:F4:0B:5A:0F:30:28:A2:80:6A:89:54:80:C1:77:41:EE:B0" for host 127.0.0.5
14:40:41 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "39:7C:F9:22:9A:12:71:DB:11:2C:93:48:6B:CF:CA:FF:4E:2F:DE:49:ED:E7:97:01:4D:B8:13:B9:0D:D5:4A:9B:F0:5B:51:16:AC:52:5A:8A:4B:3B:45:53:94:DA:3E:B7:24:9E:A2:D8:D8:6B:15:1C:43:8C:99:9D:DA:56:65:CE" for host 127.0.0.7
14:40:41 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "B1:BA:DC:6E:AB:B7:5C:05:48:54:79:4D:8F:F7:9A:82:D7:D3:D9:DC:8E:1E:7F:DD:27:C9:06:11:57:74:6B:67:B3:99:8A:30:BE:73:80:1E:1C:CB:EA:F4:6D:B6:9C:7A:6B:B5:F0:61:84:00:56:6F:79:89:7A:9C:AB:0B:46:A3" for host 127.0.0.5
14:40:42 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "07:49:5E:F2:12:CC:EC:88:C6:7F:89:E8:C1:D8:FC:9C:8C:CE:BD:EA:2C:EB:18:3A:83:93:75:63:2A:F7:EC:67:57:97:BC:72:BE:6A:9F:48:34:27:0C:59:BB:E7:23:22:B4:E9:0F:E9:9F:22:62:BC:F6:01:7F:E2:11:22:1B:08" for host 127.0.0.2
14:40:43 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "0C:A1:9F:81:F2:6B:DB:A7:36:28:7F:F2:17:1F:18:F9:54:7F:05:C5:43:1C:05:11:61:D0:58:6C:74:0A:AD:0B:C9:06:7D:E2:C2:53:93:E1:CE:10:84:C3:D2:E8:6F:D3:05:0B:4F:92:41:3A:0B:3F:B8:02:F5:02:E3:17:7D:EE" for host 127.0.0.3
14:40:46 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "A8:6D:F8:0E:5B:17:D6:00:58:C2:C6:37:0F:11:35:5D:E2:81:FA:01:21:06:6E:E1:51:A5:3C:22:49:40:46:DD:24:A8:20:0D:86:C4:0E:50:44:3D:0B:D5:BB:C9:35:65:A7:11:37:86:17:C9:41:C1:2F:A8:1D:BA:7A:EA:7C:D9" for host 127.0.0.3
14:40:46 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "B6:02:EA:A6:54:DD:E7:45:2B:DE:58:57:FE:94:BF:F3:5D:87:23:CC:BB:33:BE:75:5F:B2:CE:62:CB:C8:C5:93:11:8A:86:E9:99:CB:D0:9E:A1:2D:FC:4E:20:43:1F:09:13:8C:FB:D5:4C:98:1D:BC:E1:6D:94:D0:6B:22:E1:3E" for host 127.0.0.7
14:40:46 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "05:F4:69:13:17:AB:A8:FF:98:16:CD:9D:AC:53:1E:CA:72:6C:9A:ED:6D:98:A0:81:76:44:3D:4F:27:03:A0:2A:05:B4:EE:BC:1B:F7:E0:83:3A:28:16:55:DB:FB:CD:0C:BF:5E:18:D9:E9:51:24:58:F1:2E:B5:20:D7:8F:25:40" for host 127.0.0.2`

And here is log from 1.log:
`nohup: appending output to 'nohup.out'
flag provided but not defined: -raft`

**Comment by fixanoid** [comment]
@VladisLove1 7node examples requires initial configuration in a vagrant environment, otherwise things the scripts rely on wont work. Please either follow the steps as explained in the readme or understand the bootstrapping script and make sure your host environment matches.
