### ISSUE TITLE
Dynamic array in private contracts

### ISSUE THREAD

**Issue by cosimoth** [jpmorganchase/quorum-examples#114]
Hi team, I've successfully established a private Quorum network with the example, which runs well.
When I deploy a private contract between node 1 and node 2, with a dynamic array `string[] _data` as below 
> pragma solidity ^0.4.15;  
contract simple{  
    string[] public _data;  
    string public _info;  
    constructor(string info) {  
        _info=info;     
    }
    function put(string record) {
        _data.push(record);
    }
    function get_record(uint idx) constant returns (string retVal) {
        return _data[idx];
    }
    function get_num() constant returns (uint num) {
        return _data.length;
    }
    function get_info() constant returns (string info) {
        return _info;
    }
}

I can write `_info` with `constructor` when deploying, and read it with function `get_info()` both in node 1 and 2, while node 3 can access nothing.
Then I push a string (e.g., "abc") into `_data` with function `put("abc")`, a corresponding transaction is generated and a new block is created. After that, however, function `get_num()` returns 0, and `get_record(0)` returns an error. It seems nothing stored in `_data`. Why is that? 
Any help would be appreciated. Thanks in advance. : )

**Comment by fixanoid** [comment]
@cosimoth please dont edit the tickets contents as we are not notified about these changes -- new issues should mean new ticket =)

What genesis file are you using?

**Comment by fixanoid** [comment]
Please reopen if you are still experiencing this issue.
