### ISSUE TITLE
Error with certificate when trying expose 7 nodes to public IPs

### ISSUE THREAD

**Issue by shuangjj** [jpmorganchase/quorum-examples#115]
##Environments:
**Platform**: Azure server ubuntu 17.10
**Constellation Node** 0.3.2
Geth
Version: 1.7.2-stable
Git Commit: e8f0ee91620fbd14385d56658da249c22a9704a2
**Quorum Version**: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.8.7
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

## Description
I was trying to setup the 7nodes without vagrant and expose the nodes with public IP on Azure.
Here is the change i made on the `constellaltion-start.sh`:
```
CMD="constellation-node --url=https://VM_PUBLIC_IP:900$i/ --port=900$i --workdir=$DDIR --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://VM_PUBLIC_IP:9001/"
```
## Problem
I'm getting this tls certificate error on the constellation log and the `ApiSendRaw` error when sending private transactions:
```
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
15:36:15 [WARN] Error performing API request: ApiSendRaw (Send {sreqPayload = "`\128`@R4\128\NAKa\NUL\DLEW`\NUL\128\253[P`@Q` \128a\SOHa\131\&9\129\SOH\128`@R\129\SOH\144\128\128Q\144` \SOH\144\146\145\144PPP\128`\NUL\129\144UPPa\SOH\ETB\128a\NULJ`\NUL9`\NUL\243\NUL`\128`@R`\EOT6\DLE`SW`\NUL5|\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\144\EOTc\255\255\255\255\SYN\128c*\SUB\252\217\DC4`XW\128c`\254G\177\DC4`\128W\128cmL\230<\DC4`\170W[`\NUL\128\253[4\128\NAK`cW`\NUL\128\253[P`j`\210V[`@Q\128\130\129R` \SOH\145PP`@Q\128\145\ETX\144\243[4\128\NAK`\139W`\NUL\128\253[P`\168`\EOT\128\&6\ETX\129\SOH\144\128\128\&5\144` \SOH\144\146\145\144PPP`\216V[\NUL[4\128\NAK`\181W`\NUL\128\253[P`\188`\226V[`@Q\128\130\129R` \SOH\145PP`@Q\128\145\ETX\144\243[`\NULT\129V[\128`\NUL\129\144UPPV[`\NUL\128T\144P\144V\NUL\161ebzzr0X \167\156\US\223\135\140\200wG\DEL1\191\&2R8\178\ETX\240AA\ESCY%\vC\249\146\206\DLE\215y\223\NUL)\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL*", sreqFrom = Nothing, sreqTo = ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}); sendRequest: Errors while running sendPayload: [Left "Unknown recipient\nCallStack (from HasCallStack):\n  error, called at ./Constellation/Node.hs:162:21 in constellation-0.3.0-BnLflgEflIW2X2vn7POtes:Constellation.Node"]
```

## Questions
1. Is running 7nodes without vagrant on a single VM with different ports doable?
2. Any clue on the tls certificate issue?

Thank you!
-Shuang

**Comment by namtruong** [comment]
Hi @shuangjj ,

Thanks for raising this.

At the moment the 7 nodes example will fail the SSL handshake if the nodes run on a single VM with the same IP address (event with different ports), hence the certificate rejected message that you saw.

We are releasing a new version soon which will fix this issue. In the mean time I would suggest switching TLS configuration to off so you can have it working. This can be achieved by adding --tls=off to your args, and also changing the url from https:// to http://

Regards,
Nam
