### ISSUE TITLE
error while executing truffle migrate

### ISSUE THREAD

**Issue by manojvenkateswararaja** [jpmorganchase/quorum-examples#116]
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

my quorum node is up and running but iam facing the above error....can anyone  suggest me the solution.
this is the network setup in truffle.js
   development: {
        host: '127.0.0.1',
        port: 22000,
        network_id: '*' ,// Match any network id
        gasPrice:0,
        gas: 4500000
      },
  
      nodefour:  {
        network_id: '*',
        host: "127.0.0.1",
        port:  22003,
        gasPrice:0,
        gas:   4500000
   },

   nodeseven:  {
    network_id: '*',
    host: "127.0.0.1",
    port:  22006,
     gasPrice:0,
    gas:   4500000
},

**Comment by fixanoid** [comment]
@manojvenkateswararaja are you running quorum-examples as a vagrant environment? If so, is your truffle inside the vagrant as well?

**Comment by fixanoid** [comment]
@manojvenkateswararaja please reopen if this is still an issue.
