### ISSUE TITLE
Writing dynamic array in a private contract

### ISSUE THREAD

**Issue by cosimoth** [jpmorganchase/quorum-examples#117]
Hi team, I've successfully established a private Quorum network with the 7-nodes example, using the exactly same configuration and genesis file as in `examples/7nodes/`.
My simple contract has a string `_info`, and a dynamic string array `_data` to store something: 
> pragma solidity ^0.4.15;  
contract simple{  
    string[] public _data;  
    string public _info;  
    constructor(string info) {  
        _info=info;     
    }
    function put(string record) {
        _data.push(record);
    }
    function get_record(uint idx) constant returns (string retVal) {
        return _data[idx];
    }
    function get_num() constant returns (uint num) {
        return _data.length;
    }
    function get_info() constant returns (string info) {
        return _info;
    }
}

After the network is set up, It runs well and logs show there're no errors. Then I attach to node 2 with `geth attach qdata/dd2/geth.ipc`, and deploy a private contract instance with node 1, using compiled abi and bytecode as follows: 
>\> eth.blockNumber
0
 \> var info = "123" ;
undefined
\> web3.eth.defaultAccount = eth.accounts[0];
"0xca843569e3427144cead5e4d5999a3d0ccf92b8e"
\> var simpleContract= web3.eth.contract([{"constant":true,"inputs":[{"name":"idx","type":"uint256"}],"name":"get_record","outputs":[{"name":"retVal","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"get_num","outputs":[{"name":"num","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"record","type":"string"}],"name":"put","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get_info","outputs":[{"name":"info","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"info","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]);
undefined
\> var simple = simpleContract.new(info,{from: web3.eth.accounts[0], data: '0x608060405234801561001057600080fd5b506040516104c63803806104c683398101604052805101805161003a906001906020840190610041565b50506100dc565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061008257805160ff19168380011785556100af565b828001600101855582156100af579182015b828111156100af578251825591602001919060010190610094565b506100bb9291506100bf565b5090565b6100d991905b808211156100bb57600081556001016100c5565b90565b6103db806100eb6000396000f3006080604052600436106100615763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166310ea914281146100665780633e27a8e8146100f35780634c21eb071461011a5780636058348814610175575b600080fd5b34801561007257600080fd5b5061007e60043561018a565b6040805160208082528351818301528351919283929083019185019080838360005b838110156100b85781810151838201526020016100a0565b50505050905090810190601f1680156100e55780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3480156100ff57600080fd5b50610108610235565b60408051918252519081900360200190f35b34801561012657600080fd5b506040805160206004803580820135601f810184900484028501840190955284845261017394369492936024939284019190819084018382808284375094975061023c9650505050505050565b005b34801561018157600080fd5b5061007e610282565b606060008281548110151561019b57fe5b600091825260209182902001805460408051601f60026000196101006001871615020190941693909304928301859004850281018501909152818152928301828280156102295780601f106101fe57610100808354040283529160200191610229565b820191906000526020600020905b81548152906001019060200180831161020c57829003601f168201915b50505050509050919050565b6000545b90565b6000805460018101808355918052825161027d917f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e56301906020850190610317565b505050565b60018054604080516020601f6002600019610100878916150201909516949094049384018190048102820181019092528281526060939092909183018282801561030d5780601f106102e25761010080835404028352916020019161030d565b820191906000526020600020905b8154815290600101906020018083116102f057829003601f168201915b5050505050905090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061035857805160ff1916838001178555610385565b82800160010185558215610385579182015b8281111561038557825182559160200191906001019061036a565b50610391929150610395565b5090565b61023991905b80821115610391576000815560010161039b5600a165627a7a723058206e443994307aeef494a844cf5c933114426d8c6ba6823ee175aeb96a5c1676090029', gas: '4700000', privateFor: ["BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="]});

Herein, `"BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="` is the public key of node 1, which is same as that of 7-nodes example.  
The private contract is deployed and a new block is generated. I can get its address, and read string `_info` and the length of dynamic array `_data` as:
>\> eth.blockNumber
1
\>  simple.address
"0x341ed42cdfb13b897a198cd1c87ddf070e25e6a1"
\> simple.get_info()
"123"
\> simple.get_num()
0

Till now everything is fine. Then I push a string "abc" into `_data` with function `put("abc")`:
> \> simple.put("abc")
"0xe765af6ba9d67389341b4b17f8d0db5eb68d5a042beeb5813174ae3704e39a5c"
\> eth.blockNumber
2
\> simple.get_num()
0
\> simple.get_record(0)
Error: new BigNumber() not a base 16 number:
    at L (bignumber.js:3:2876)
    at bignumber.js:3:8435
    at a (bignumber.js:3:389)
    at web3.js:1110:23
    at web3.js:1634:20
    at web3.js:826:16
    at map (<native code>)
    at web3.js:825:12
    at web3.js:4080:18

A corresponding transaction is generated and a new block is created. However, function `get_num()` still returns 0, and `get_record(0)` returns an error. It seems nothing stored in `_data`.   
Why is that? Is there any thing wrong with my contract?

Any help would be appreciated. Thanks a lot. : )

**Comment by cosimoth** [comment]
I've checked that there's no new logs in `constellation2.log` (new fingerprints of peers are successfully added).  I'm not sure `2.log` is normal: 
> TRACE[08-10|03:48:53] Node Permissioning is Enabled.
TRACE[08-10|03:48:53] Node Permissioning                       Connection Direction=OUTGOING
DEBUG[08-10|03:48:53] parsePermissionedNodes                   DataDir=/home/vmadmin/quorum-examples/examples/7nodes/qdata/dd2 file=permissioned-nodes.json
DEBUG[08-10|03:48:53] isNodePermissioned                       permissionedList="[ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef 0ba6b9f606a43a95edc6247cdb1c1e105145817be7bcafd6b2c0ba15d58145f0dc1a194f70ba73cd6f4cdd6864edc7687f311254c7555cc32e4d45aeb1b80416 579f786d4e2830bbcc02815a27e8a9bacccc9605df4dc6f20bcc1a6eb391e7225fff7cb83e5b4ecd1f3a94d8b733803f2f66b7e871961e7b029e22c155c3a778 3d9ca5956b38557aba991e31cf510d4df641dce9cc26bfeb7de082f0c07abb6ede3a58410c8f249dabeecee4ad3979929ac4c7c496ad20b8cfdd061b7401b4f5 3701f007bfa4cb26512d7df18e6bbd202e8484a6e11d387af6e482b525fa25542d46ff9c99db87bd419b980c24a086117a397f6d8f88e74351b41693880ea0cb eacaa74c4b0e7a9e12d2fe5fee6595eda841d6d992c35dbbcc50fcee4aa86dfbbdeff7dc7e72c2305d5a62257f82737a8cffc80474c15c611c037f52db1a3a7b 239c1f044a2b03b6c4713109af036b775c5418fe4ca63b04b1ce00124af00ddab7cc088fc46020cdc783b6207efe624551be4c06a994993d8d70f684688fb7cf]"
DEBUG[08-10|03:48:53] isNodePermissioned                       connection=OUTGOING nodename=0ba6b9f606a43a95edc6247cdb1c1e10 DENIED-BY=0ba6b9f606a43a95edc6247cdb1c1e10
DEBUG[08-10|03:48:53] isNodePermissioned                       connection=OUTGOING nodename=0ba6b9f606a43a95edc6247cdb1c1e10 ALLOWED-BY=0ba6b9f606a43a95edc6247cdb1c1e10
TRACE[08-10|03:48:53] Rejected peer before protocol handshake  id=0ba6b9f606a43a95 addr=127.0.0.1:21001 conn=staticdial err="connected to self"
TRACE[08-10|03:48:53] Dial task done                           task="staticdial 0ba6b9f606a43a95 127.0.0.1:21001"
TRACE[08-10|03:48:53] New dial task                            task="wait for dial hist expire (29.9999981s)"

**Comment by fixanoid** [comment]
This might be a solidity syntax issue, I'll check later, but another thing is that you need to put info array when you transact with the contract, so your call should be like so:

`simple.put("abc",{from:eth.coinbase, privateFor: ["BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="]})`

**Comment by cosimoth** [comment]
@fixanoid It works! Thx a lot.
