### ISSUE TITLE
Sending Private transaction crashes the network

### ISSUE THREAD

**Issue by Prabhat-Sutar** [jpmorganchase/quorum-examples#119]
Hi,
I have deployed a simple contract from truffle   
`deployer.deploy(SampleContract,{privateFor:['QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=',
  '1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=',
  'oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8=',
  'R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=',
  'UfNSeSGySeKg11DVNEnqrUtxYRVor4+CvluI8tVv62Y=',
  'ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=']})`

but on sending transaction with `privateFor` having one or more key crashes the network, although it works when `privateFor` has keys of all the 6 recipients.

**Comment by fixanoid** [comment]
@Prabhat-Sutar this issue has been resolved on master. There are several ways to update quorum-examples vm's Quorum:

1. In vagrant guest env, cd into ~/quorum and git checkout master. Then make all, and then replace executable with sudo cp build/bin/geth /usr/local/bin
2. Another way is to comment this line in the boostrap.sh: https://github.com/jpmorganchase/quorum-examples/blob/master/vagrant/bootstrap.sh#L35 and rebuild your guest vagrant
