### ISSUE TITLE
Can we send private transactions between accounts, just like we send between nodes

### ISSUE THREAD

**Issue by TFPoC** [jpmorganchase/quorum-examples#12]
I am trying to send private transactions between accounts just like nodes.
But not able to do it.

**Comment by patrickmn** [comment]
Currently, private transactions must be addressed to a set of transaction manager (Constellation) public keys.

**Comment by TFPoC** [comment]
Is there any plans, to add the feature of private transaction between accounts, in quorum platform, in near future?

**Comment by patrickmn** [comment]
Not currently.
