### ISSUE TITLE
Internal Server Error when trying to run private contract script

### ISSUE THREAD

**Issue by hshar7** [jpmorganchase/quorum-examples#124]
I am having an error when I try to run `./runscript.sh private-contract.js`
Error:
```
err creating contract Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 02 Oct 2018 16:31:26 GMT] Server:[Warp/3.2.13]] Body:0xc420656440 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc420082a00 TLS:<nil>}
```
Steps to reproduce: (On the supplied Vagrant setup:)
- ./constellation-start.sh
- ./istanbul-init.sh
- ./istanbul-start.sh
-  ./runscript.sh private-contract.js 

Any help is greatly appreciated

**Comment by fixanoid** [comment]
Hi @hshar7 you don't need to run constellation start manually, its part of the start scripts. So, in your env, run ./stop.sh and then init and start again.

**Comment by hshar7** [comment]
Thanks @fixanoid that seems to have fixed it!
Any idea why the error is not detailed? It doesn't tell me anything!

**Comment by fixanoid** [comment]
Hey, so the error would be detailed in the error log and what you are seeing is actually report from the ipc post that quorum client made to the constellation it thought as its own. That said, we should probably make it clearer =)

**Comment by hshar7** [comment]
@fixanoid please let me know how to access the error log!

**Comment by SatpalSandhu61** [comment]
The error logs are in the qdata/logs directory.
