### ISSUE TITLE
Quorum 7 nodes Example Transaction History

### ISSUE THREAD

**Issue by subhamghosh** [jpmorganchase/quorum-examples#125]
How can I check Transaction history on a block ? Currently there is documentation on **Checking the state of the contract** in the 7 nodes page. I can check the current transaction. I want to check all the previous transaction send using a contract. How to check all the past transactions ?

**Comment by fixanoid** [comment]
@subhamghosh this isn't Quorum specific as such, rather a set of helper APIs bundled in the geth / web3 clients. Please see: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter
