### ISSUE TITLE
7nodes with docker-compose

### ISSUE THREAD

**Issue by CarlosLanderas** [jpmorganchase/quorum-examples#132]
Hi, I was trying to test the 7nodes samples using docker and I get the following error when executing 
> docker-compose up -d

panic: MustNew: Failed to connect to Constellation (/qdata/tm/tm.ipc): lstat /qdata/tm/tm.ipc: no such file or directory

What do I need for the sample to work?. Shouldn't it just work when using docker?.

**Note**: I am using docker for Windows, might that be the problem?.

**UPDATE**: I just followed the steps in Ubuntu and everything is working fine, so I guess it is not compatible with Windows?. If so, maybe it should be explained on the README installation steps.

Thank you very much.

**Comment by trung** [comment]
Thanks, @CarlosLanderas. I've raised a PR to update the docs.

**Comment by vietlq** [comment]
This error is due to race condition at start-up time:

```
panic: MustNew: Failed to connect to Constellation (/qdata/tm/tm.ipc): lstat /qdata/tm/tm.ipc: no such file or directory
```

I ran on macos Mojave and I see the error repeating for a few times on each docker instance until the file `/qdata/tm/tm.ipc` is created for each instance.

**Comment by vietlq** [comment]
I will try if it works on Windows :) The false alarm error here made me quite nervous when running on macos too.

**Comment by vietlq** [comment]
@CarlosLanderas you can run on Windows if you take my PR or my branch: https://github.com/jpmorganchase/quorum-examples/pull/144

**Comment by CarlosLanderas** [comment]
I'm gonna try it. Thank you @vietlq

**Comment by CarlosLanderas** [comment]
@vietlq  It seems to work!. The problem is when I execute docker-compose up when all nodes and txmanagers are ready Docker for windows hangs forever. While it's starting I've been able to random connect to some nodes between 22000 and 22006 ports using geth but when all are ready Docker just dies...

The fix seems to be good for windows, as I've never seen this behaviour but it must be related to having 14 containers executing at the same tame.

I am using a computer with I7 6700K CPU and 16GB ram.

@vietlq if I want to use the 7nodes sample with just 3 nodes, the only thing I have to change is the services and volume declarations in docker-compose and the [peer list](https://github.com/vietlq/quorum-examples/blob/master/docker-compose.yml#L114) to use only 3 txmanagers right?

**Comment by CarlosLanderas** [comment]
@vietlq executing only 3 nodes with 3 txmanagers seems to work nice for me. Thanks for the PR!

**Comment by CarlosLanderas** [comment]
@vietlq executing only 3 nodes with 3 txmanagers seems to work nice for me. 
I can send transactions but I can never get the transactionReceipt (always null), but I guess something is missconfigured on the docker-compose when reducing nodes and txmanagers

Thanks for the PR!
