### ISSUE TITLE
How to deploy 7nodes in multiple servers?

### ISSUE THREAD

**Issue by coolcode** [jpmorganchase/quorum-examples#137]
I modified the 7nodes example and tried deploying it in multiple servers.
SourceCode hosted on github: https://github.com/coolcode/quorum-examples/tree/master/simple

In my demo, I use only 3 servers to deploy node1, node2 & node3.

IP | Node | Open Ports
-- | -- | --
52.205.202.193 | node1 | 21000,22000,22002,22003
107.22.137.136 | node2 | 21000,22000,22002,22003
54.159.102.185 | node3 | 21000,22000,22002,22003

There were two scripts file I changed by myself -- [init.sh](https://github.com/coolcode/quorum-examples/blob/master/simple/init.sh) & [start.sh](https://github.com/coolcode/quorum-examples/blob/master/simple/start.sh)

the peer settings in init.sh (line 97):

```
"peer": [
        {
            "url": "http://52.205.202.193:22003"
        },
        {
            "url": "http://107.22.137.136:22003"
        },
        {
            "url": "http://54.159.102.185:22003"
        }
    ]
```

Also, modify the IP address in permissioned-nodes.json

```
[
	"enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@52.205.202.193:21000?discport=0&raftport=22002",
	"enode://0ba6b9f606a43a95edc6247cdb1c1e105145817be7bcafd6b2c0ba15d58145f0dc1a194f70ba73cd6f4cdd6864edc7687f311254c7555cc32e4d45aeb1b80416@107.22.137.136:21000?discport=0&raftport=22002",
	"enode://579f786d4e2830bbcc02815a27e8a9bacccc9605df4dc6f20bcc1a6eb391e7225fff7cb83e5b4ecd1f3a94d8b733803f2f66b7e871961e7b029e22c155c3a778@54.159.102.185:21000?discport=0&raftport=22002"
]
```

In node1, initialize and start node1:

```
cd ~/qm/simple
./init.sh --node 1 && ./start.sh --node 1
```

In node2, initialize and start node2:

```
cd ~/qm/simple
./init.sh --node 2 --permissioned 0 && ./start.sh --node 2 --permissioned 0
```

In node3, initialize and start node3:

```
cd ~/qm/simple
./init.sh --node 3 --permissioned 0 && ./start.sh --node 3 --permissioned 0
```

Testing
Step1.Sending a private transaction
In node 1, (this is denoted by the public key passed via privateFor: ["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="] in private-contract.js):

`./runscript.sh private-contract.js`

Make note of the TransactionHash printed to the terminal.
Step2.Inspecting the Quorum nodes

We can inspect any of the Quorum nodes by using geth attach to open the Geth JavaScript console. For this demo, we will be inspecting Node 1, Node 2 and Node 3.

It is recommended to use separate terminal windows for each node we are inspecting. In each terminal, ensure you are in the ~/qm/simple/ directory, then:

In terminal 1 run `geth attach qdata/dd/geth.ipc` to attach to node 1
In terminal 2 run `geth attach qdata/dd/geth.ipc` to attach to node 2
In terminal 3 run `geth attach qdata/dd/geth.ipc` to attach to node 3

Step3.Checking the state of the contract
For each of the 3 nodes we'll use the Geth JavaScript console to create a variable called address which we will assign to the address of the contract created by Node 1. The contract address can be found in step 2.

Once you've identified the contract address, run the following command in each terminal:

`> var address = "0xfe0602d820f42800e3ef3f89e1c39cd15f78d283"; //replace with your contract address `
Next we'll use eth.contract to define a contract class with the simpleStorage ABI definition in each terminal:

```
> var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
> var private = eth.contract(abi).at(address)
```

The function calls are now available on the contract instance and you can call those methods on the contract. Let's start by examining the initial value of the contract to make sure that only nodes 1 and 2 can see the initialized value.

In terminal window 1 (Node 1):
> private.get()
> 42

In terminal window 2 (Node 2):
> private.get()
> 0 ❌!ERROR! 
**(But the expected result should be 42, not 0!)** 

In terminal window 3 (Node 3):
> private.get()
> 0

Normally nodes 1 and 2 are able to read the state of the private contract and its initial value is 42. I have tried lots of times but it is still 0. 

Can you tell me which step has problem? or please tell me how to deploy 7nodes sample in multiple servers?

**Comment by SatpalSandhu61** [comment]
Hi, I checked out your example and it seems to work okay for me.
I only have one machine, so I had to modify your scripts to run all 3 nodes on the same server (which pretty much mirrors the 7-nodes example).
I get the expected value of 42 from private.get() on node 2.

Some things for you to check:
1) Which version of Quorum are you using? If it's not the latest then retry with the v2.1.1 or master.
2) Are there any errors in the geth logs or the tessera logs? There should be no messages indicating that any node is unable to connect.
3) After submitting the private contract, check the transaction receipt to confirm that it was processed ok.
4) Check the tessera logs to confirm that node 2 accepted it ok. You should see a message something like the following to show that the transaction was stored:
```
Stored transaction MwgMeJBWEBuVccJ9JpQ59XbKrPXQFn2yK1qh16O6DAJq3FtWm/AedgSYZyrJ35UnV75wI8XnStukF36ZDVqkkQ==
```
Where the key is the same as the value in the tessera1.log.

**Comment by fixanoid** [comment]
Please reopen if theres a pending question.
