### ISSUE TITLE
Question: private state partially updated

### ISSUE THREAD

**Issue by ivica7** [jpmorganchase/quorum-examples#14]
Hello Quorum experts.

I'm just wondering if it is possible to construct the following situation in Quorum (based on SimpleStorage privacy example):

Step 1:
from:N1 privateFor:N2,N3 - instantiate new contract
N2, N3 can call get on the contract and will see the same number: 42

Step 2:
from:N1 privateFor:N2 - set(73)
I assume N2 calling get will see 73
But what about N3? Will his get still return 42?

Regards,
Ivica

**Comment by patrickmn** [comment]
Hi Ivica,

Yes, that is correct. Currently, you have to track the parties yourself, and, in most cases, you'll want to keep that recipient list constant.

In the future, we plan to build in tracking of participating parties, as well as asserting that state matches between them. There are some cases where you might *want* the state to deviate, but the default will likely be to check that the state root for a contract is identical on all participating nodes.
