### ISSUE TITLE
raft-start.sh doesn't start when using geth v1.8.11-stable

### ISSUE THREAD

**Issue by saikatsain** [jpmorganchase/quorum-examples#147]
7 node example using the geth v1.8.11-stable version does not work as the following below parameters are not available.

--raft
--raftport value
--emitcheckpoints

The build worked on geth v1.7.2.

Is there any plan to update the pre-requisites to specify the verison of geth to be used or is there any changes expected on the raft-start.sh to allow the code to work with the latest geth version,

**Comment by SatpalSandhu61** [comment]
Hi, can you clarify where you're getting that v1.8.11 version from? We don't have a v1.8.11 release of quorum... If you mean that you're running a bare upstream ethereum geth with quorum-examples, then I don't believe that will work.
Those command line options work fine for all the released Quorum versions and for master.
FYI master includes a merge of upstream geth v1.8.12

**Comment by saikatsain** [comment]
Thank you for clarifying.

I had been referring to [link](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) and was not able to find the parameters and had used the bare upstream etherium geth with quorum-examples.

I will check with the quorum version and get back. Thanks.

**Comment by SatpalSandhu61** [comment]
Ok, that explains it.
You should use quorum geth with quorum-examples: https://github.com/jpmorganchase/quorum
The raft command line options are under the Raft consensus docs in the quorum wiki: https://github.com/jpmorganchase/quorum/blob/master/docs/raft.md
