### ISSUE TITLE
Not able to deploy contracts on 7 nodes using truffle

### ISSUE THREAD

**Issue by vasa-develop** [jpmorganchase/quorum-examples#148]
**Configuration Used**
-------------------------------------------------------
**geth version**
Geth
Version: 1.8.12-stable
Git Commit: df03a37833d127f5e5140eaab4d1dfcb56301695
Quorum Version: 2.1.1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.1
Operating System: linux
GOPATH=/home/ubuntu/gopath
GOROOT=/home/ubuntu/go

**OS**
Ubuntu 16.10 LTS

**7 nodes commit version**
commit 1cd6232bf997e462b3a802f2200f0d5b44dbabc8
Author: Nguyen Kien Trung <trung.n.k@gmail.com>
Date:   Mon Dec 10 15:49:17 2018 -0500

publish third party port for raw transaction support (#145)

----------------------------------------
Issue faced:
I was trying to deploy a contract using truffle on a 7 nodes config(deployed on a server). I have opened the RPC ports for accessing them remotely(also configured the CORS). Now, if I try to deploy a contract on the 7 nodes, it doesn't get through. The node logs show that it received the transaction request, but next block is not mined; thus the transaction doesn't get through.(here is the [truffle log](http://gateway.ipfscloud.store/ipfs/Qmf2QM3PPwiMQmr5kEtZx2xgBy7njLdqLCir27kvBf9tTj))

When I tried it with web3.js and web3j, it worked fine.
is there some issue with the truffle implementation?

**Comment by fixanoid** [comment]
@vasa-develop so with Quorum running in raft mode we have noticed that truffle gets "stuck". I believe the reason is that its waiting for additional blocks to confirm the txn, but I haven't looked into it closer than that. An easy way to fix this in your development environment is to run Istanbul instead of raft, but if you're keen on using raft, we also noticed that sending an unrelated txn through the node will allow truffle to proceed (a txn like value transfer or whatever).

Please let me know if this helps.

**Comment by vasa-develop** [comment]
@fixanoid  Yeah, that's exactly what I have found(sending an unrelated trx. gets it through). I will look into Istanbul and get back here soon.

**Comment by ghost** [comment]
@vasa-develop 
I have the same issue and I would be very thankful if you could please share the code snippet, which fixed this problem.

**Comment by fixanoid** [comment]
@saitam1 theres no particular code snippet, but if your truffle seems stuck, you could console into any of the nodes and execute a value transfer.

**Comment by ghost** [comment]
OK then its different, it does not stuck... After I press enter on `truffle deploy`, it seems that truffle is doing something for about 10 seconds, then it ends the process and returns just nothing to the terminal, so I just can't find out whats the issue
