### ISSUE TITLE
Raft 7 nodes don't mining block

### ISSUE THREAD

**Issue by maojun9** [jpmorganchase/quorum-examples#150]
Hi,

I have quorum 7 nodes example running on a ubuntu system, with RAFT consensus. After I tun "./raft-start.sh tessera", everything runs fine and 7 nodes a up. Then I run "./runscript.sh private-contract.js", I got the TransactionHash and waiting to be mined. But when I use "geth attach qdata/dd1/geth.ipc" to attach node 1, I find the raft doesn't work, it never mining a block. I check eth.blockNumber, it always stay 0 and raft.leader returns error: no leader is currently elected. 

What am I missing to get block mined?

**Comment by SatpalSandhu61** [comment]
It sounds like all your nodes aren't running. If all your nodes are not running and there is no raft leader then it won't mint any blocks.
Check whether you have all 7 geth instances running. I suggest you examine your log files for an error message.
