### ISSUE TITLE
make *** [geth] Error 1 in OSx

### ISSUE THREAD

**Issue by lrgeoemtry** [jpmorganchase/quorum-examples#151]
ran commands to clone and install quorum examples locally. 
when i ran make 
there was an error thrown labeled in the title. 

picture of my env attached. 

any help is appreciated.

**Comment by lrgeoemtry** [comment]
<img width="573" alt="screenshot 2019-01-06 at 5 55 26 pm" src="https://user-images.githubusercontent.com/25958096/50743074-42f24c00-11e1-11e9-8742-e1eb085eed1d.png">

**Comment by fixanoid** [comment]
@lrgeoemtry hi, the commands should be executed inside the vagrant, and the error shot you've given appears to be running it from your host os. Please switch to vagrant and try again. Thanks.
