### ISSUE TITLE
Error in compiling quorum 

### ISSUE THREAD

**Issue by vaibhav-eleven** [jpmorganchase/quorum-examples#155]
Getting the below error after running make all command.

build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=d77cb778cafe2140badf444ffa429cc1882c9079 -v ./cmd/geth
# github.com/ethereum/go-ethereum/cmd/geth
github.com/ethereum/go-ethereum/crypto/bn256/cloudflare.gfpMul: relocation target runtime.support_bmi2 not defined
util.go:45: exit status 2
exit status 1
make: *** [geth] Error 1

**Comment by fixanoid** [comment]
@vaibhav-eleven is this inside the vagrant env or outside? What go version are you using and what host os is this?

**Comment by vaibhav-eleven** [comment]
This is outside vagrant env. 
go version go1.11.1
os - ubuntu 16.04.5

**Comment by SatpalSandhu61** [comment]
@vaibhav-eleven we don't yet support building with go 1.11, suggest you use 1.9.7.
Note that there is an PR open to enable support for building with 1.11, so it's on the way.
