### ISSUE TITLE
constellation-node: error while loading shared libraries: libsodium.so.18

### ISSUE THREAD

**Issue by samanshahmohamadi** [jpmorganchase/quorum-examples#157]
When running `constellation-node`, I get this error:

> constellation-node: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory

The *-start.sh scripts not running successfully because of the error.

**Comment by samanshahmohamadi** [comment]
Solved by reinstalling `libsodium-dev` and renaming the `libsodium.so` file to `libsodium.so.18` in `/usr/lib/x86_64-linux-gnu` directory.

**Comment by iasinDev** [comment]
Thanks!!!!
