### ISSUE TITLE
Examples do not work with latest Constellation

### ISSUE THREAD

**Issue by vjrantal** [jpmorganchase/quorum-examples#16]
If using the latest Constellation from https://github.com/jpmorganchase/constellation private transactions start failing to "Unknown recipient"-error. This is because the sample configurations have something like:

```
archivalPublicKeyPath = "keys/tm1a.pub"
archivalPrivateKeyPath = "keys/tm1a.key"
```

Even though the archival feature is removed from latest Constellation, the public key from the config gets picked up due to this line:

https://github.com/jpmorganchase/constellation/blob/e6aed2ba7590d034c7213cfc86a940931e627ef0/Constellation/Node/Config.hs#L69

This causes all private transactions to be tried to be sent to `keys/tm1a.pub` which nobody advertise so all private transactions fails.

Fix proposal is to edit the examples by removing the usage of the archival feature.

**Comment by patrickmn** [comment]
There is another possible solution, which is to automatically put the archival private/pub key pair in the key pair arrays and listing the pub key in alwayssendto in the 0.0.1-config conversion handler, which would emulate the original behavior of archiving transactions.

I do think that the examples should be updated to the new config regardless once Constellation has its next release, but it would be nice to have full backwards compatibility with the old format...

**Comment by patrickmn** [comment]
If you pull from master, the archival keypair should be hosted like any other, and the public key put in alwayssendto: https://github.com/jpmorganchase/constellation/pull/34

I hope you agree this addresses the problem. (Documentation notwithstanding.)

**Comment by vjrantal** [comment]
> I hope you agree this addresses the problem. (Documentation notwithstanding.)

Thanks for the fix and I agree this addresses the problem. I didn't yet test, but based on looking at the code, the examples should now work with latest Constellation since the archival keys should be now advertised.
