### ISSUE TITLE
Docker exec geth attach ipc issue

### ISSUE THREAD

**Issue by serverlessnomad** [jpmorganchase/quorum-examples#163]
Docker exec issues the following warning and fails to attach.  Documentation for examples should be updated to reflect the need for the "ipc" prefix.

Problem:
λ docker exec -it quorum-examples_node2_1 geth attach /qdata/dd/geth.ipc
Fatal: Unable to attach to remote geth: no known transport for URL scheme "c"

Solution:
docker exec -it quorum-examples_node1_1 geth attach ipc:/qdata/dd/geth.ipc

**Comment by trung** [comment]
If the scheme is not specified, `geth` will default to `ipc`. Prefix `ipc` is known to be in Geth < 1.5

@serverlessnomad can you paste the output of `docker info` here? 

Just try to understand the root cause of this, nevertheless I'll update the doc to make it explicit.

**Comment by fixanoid** [comment]
Please reopen if this is still relevant
