### ISSUE TITLE
Node 1 is not yet listening on tm.ipc

### ISSUE THREAD

**Issue by jiebanghan** [jpmorganchase/quorum-examples#164]
when I run ./tessera-start.sh, it shows:

{ 7nodes } master » ./tessera-start.sh                                                                        /c/tools/src/github.com/quorum-examples/examples/7nodes
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c2/tessera-config2.json >> qdata/logs/tessera2.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c3/tessera-config3.json >> qdata/logs/tessera3.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c4/tessera-config4.json >> qdata/logs/tessera4.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c5/tessera-config5.json >> qdata/logs/tessera5.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c6/tessera-config6.json >> qdata/logs/tessera6.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c7/tessera-config7.json >> qdata/logs/tessera7.log 2>&1 &
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc

{ 7nodes } master » cat qdata/logs/tessera1.log                                                               
Error: Unable to access jarfile /home/vagrant/tessera/tessera.jar

but /home/vagrant/tessera/tessera.jar is there . So how to solve it? Thank you .

**Comment by SatpalSandhu61** [comment]
What are the permissions on /home/vagrant/tessera/tessera.jar ? (Do an 'ls -l' and supply the details).

Also, please supply more details - what environment you are running on, Tessera version etc.

**Comment by jiebanghan** [comment]
{ 7nodes } master » ls -l /home/vagrant/tessera/tessera.jar                                                   /c/tools/src/github.com/quorum-examples/examples/7nodes
-rwxrwxr-x+ 1 root None 50996421 Feb 25 17:32 /home/vagrant/tessera/tessera.jar
The tessera's version is the latest version, and I am on Windows10，I run the command via babun(a windows shell).

**Comment by jiebanghan** [comment]
So I have to explain that I don't use vagrant, I just compiled tessera via maven on Windows10 and compiled  
 quorum via goland on Windows10. 
I compiled tessera below:
{ target }  » ls -ltr                                                                                                         /c/tools/src/tessera/tessera-app/target
total 49823
drwxr-xr-x 1 root None        0 Feb 25 09:52 maven-status
drwxr-xr-x 1 root None        0 Feb 25 09:52 generated-sources
drwxr-xr-x 1 root None        0 Feb 25 09:52 classes
-rw-r--r-- 1 root None     5959 Feb 25 09:52 checkstyle-checker.xml
-rw-r--r-- 1 root None      282 Feb 25 09:52 checkstyle-suppressions.xml
-rw-r--r-- 1 root None      295 Feb 25 09:52 checkstyle-result.xml
-rw-r--r-- 1 root None      442 Feb 25 09:52 checkstyle-cachefile
drwxr-xr-x 1 root None        0 Feb 25 09:52 generated-test-sources
drwxr-xr-x 1 root None        0 Feb 25 09:52 test-classes
drwxr-xr-x 1 root None        0 Feb 25 09:52 maven-archiver
-rw-r--r-- 1 root None     7570 Feb 25 09:52 tessera-app-0.9-SNAPSHOT.jar
-rw-r--r-- 1 root None 50996421 Feb 25 09:53 tessera-app-0.9-SNAPSHOT-app.jar
{ target }  » pwd                                                                                                             /c/tools/src/tessera/tessera-app/target
/c/tools/src/tessera/tessera-app/target

After compilation, I copy  tessera-app-0.9-SNAPSHOT-app.jar to  /home/vagrant/tessera/tessera.jar.

**Comment by jiebanghan** [comment]
By the way, I found some error when compiling tessera but finally  I got successful compilation, I should thank to [prd-fox](/prd-fox)(https://github.com/jpmorganchase/tessera/issues/638). Thank you.

**Comment by SatpalSandhu61** [comment]
I can see that you're building Tessera as root user. I would advise against that, as it will cause permission problems.
I suggest using a non-root user. You should also run it as a non-root user.

I don't know of anyone who has run it under babun; that could present further challenges.

**Comment by fixanoid** [comment]
So, at the moment, there is no support for ipcs on windows, so unless you emulate an environment that has those, you will not be able to run tessera/c11n with Quorum. that said, if you want to launch Quorum on windows, that is possible if you set PRIVATE_CONFIG to ignore.

On windows, with conjunction with 7node example, I use this start script
```
set NETWORK_ID=10

mkdir qdata\logs

echo "[*] Starting Ethereum nodes with ChainID and NetworkId of %NETWORK_ID%"

set ARGS=--ipcdisable --nodiscover --istanbul.blockperiod 5 --networkid %NETWORK_ID% --syncmode full --mine --minerthreads 1 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul

set PRIVATE_CONFIG=ignore

START /B "i1" geth --datadir qdata/dd1 %ARGS% --rpcport 22000 --port 21000 --unlock 0 --password passwords.txt 2>>qdata/logs/1.log
START /B "i2" geth --datadir qdata/dd2 %ARGS% --rpcport 22001 --port 21001 --unlock 0 --password passwords.txt 2>>qdata/logs/2.log
START /B "i3" geth --datadir qdata/dd3 %ARGS% --rpcport 22002 --port 21002 --unlock 0 --password passwords.txt 2>>qdata/logs/3.log
START /B "i4" geth --datadir qdata/dd4 %ARGS% --rpcport 22003 --port 21003 --unlock 0 --password passwords.txt 2>>qdata/logs/4.log
START /B "i5" geth --datadir qdata/dd5 %ARGS% --rpcport 22004 --port 21004 --unlock 0 --password passwords.txt 2>>qdata/logs/5.log
START /B "i6" geth --datadir qdata/dd6 %ARGS% --rpcport 22005 --port 21005 --unlock 0 --password passwords.txt 2>>qdata/logs/6.log
START /B "i7" geth --datadir qdata/dd7 %ARGS% --rpcport 22006 --port 21006 --unlock 0 --password passwords.txt 2>>qdata/logs/7.log
echo "All nodes configured. See 'qdata/logs' for logs, and run e.g. 'geth attach qdata/dd1/geth.ipc' to attach to the first Geth node."
echo "To test sending a private transaction from Node 1 to Node 7, run './runscript.sh private-contract.js'"
```
