### ISSUE TITLE
Is there a way to connect the contract with UI or external API?

### ISSUE THREAD

**Issue by kumarashishgarg** [jpmorganchase/quorum-examples#17]

**Comment by patrickmn** [comment]
It isn't possible for a contract to communicate with the outside world, but your applications, be they UIs or APIs, can inspect the state of the contract and act based upon it.

Please see https://ethereum.stackexchange.com/questions/122/how-to-create-a-dapp-from-scratch-on-ethereum

**Comment by kumarashishgarg** [comment]
Thanks..I will try that out
