### ISSUE TITLE
Waiting until all Tessera nodes are running...

### ISSUE THREAD

**Issue by jiebanghan** [jpmorganchase/quorum-examples#182]
#### System information
Geth version: `geth version`
Version: 1.8.18-stable
OS & Version: Windows/Linux/OSX
Linux ubuntu 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

when I compiled tessera , and then I run the command below:
./raft-start.sh tessera --tesseraOptions "--tesseraJar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar"

it shows below and how to  solve it?
[*] Starting Tessera nodes
Tessera version (extracted from manifest file): 0.10-SNAPSHOT
Config type -09-
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c1/tessera-config-09-1.json >> qdata/logs/tessera1.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c2/tessera-config-09-2.json >> qdata/logs/tessera2.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c3/tessera-config-09-3.json >> qdata/logs/tessera3.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c4/tessera-config-09-4.json >> qdata/logs/tessera4.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c5/tessera-config-09-5.json >> qdata/logs/tessera5.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c6/tessera-config-09-6.json >> qdata/logs/tessera6.log 2>&1 &
java   -Xms128M -Xmx128M -jar /home/sundongyi/go_project/tessera-master/tessera-dist/tessera-app/target/tessera-app-0.10-SNAPSHOT-app.jar -configfile qdata/c7/tessera-config-09-7.json >> qdata/logs/tessera7.log 2>&1 &
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 2 is not yet listening on tm.ipc
Node 3 is not yet listening on tm.ipc
Node 4 is not yet listening on tm.ipc
Node 5 is not yet listening on tm.ipc
Node 6 is not yet listening on tm.ipc
Node 7 is not yet listening on tm.ipc
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 2 is not yet listening on tm.ipc
Node 3 is not yet listening on tm.ipc
Node 4 is not yet listening on tm.ipc
Node 5 is not yet listening on tm.ipc
Node 6 is not yet listening on tm.ipc
Node 7 is not yet listening on tm.ipc
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 2 is not yet listening on tm.ipc
Node 3 is not yet listening on tm.ipc
Node 4 is not yet listening on tm.ipc
Node 5 is not yet listening on tm.ipc
Node 6 is not yet listening on tm.ipc
Node 7 is not yet listening on tm.ipc

**Comment by zhliao** [comment]
Hi,

I go the same issue as you. If you have solved this question, could you give me some advice? Thank you.

**Comment by prd-fox** [comment]
@zhliao please open a new issue
