### ISSUE TITLE
on running command  sudo ./raft-init.sh [] Cleaning up temporary data directories [] Configuring node 1 (permissioned) ./raft-init.sh: line 15: geth: command not found  need help..

### ISSUE THREAD

**Issue by sherrygarg** [jpmorganchase/quorum-examples#183]
#### System information
Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

Environment: docker, vagrant, host os

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Backtrace
````
[backtrace]
````

**Comment by prd-fox** [comment]
Hi @sherrygarg 

Where are you running this from? e.g. inside docker, vagrant or on the host OS?

**Comment by prd-fox** [comment]
If you are running on the host OS, then you need to install Quorum first, **and make sure the it is on path**. Please refer to these instructions on how to do that: https://github.com/jpmorganchase/quorum-examples#setting-up-locally

If you are running inside vagrant, then the initialisation may not have worked properly. Try destroying the machine with `vagrant destroy` and then recreating the machine with `vagrant up`. If any error occurs during initialisation, you should see some output on the console, and then paste it here.

Thanks!

**Comment by fixanoid** [comment]
Please reopen if theres still an issue.
