### ISSUE TITLE
docker-compose accounts dismissed 

### ISSUE THREAD

**Issue by ali-esmaily** [jpmorganchase/quorum-examples#185]
I deployed quorum according to the documentation via docker-compose. I upped docker-compose and then added 2 accounts via login to quorum-examples_node1_1 and "geth --datadir /qdata/dd account new" and verified account creation via "docker exec -it quorum-examples_node1_1 geth attach /qdata/dd/geth.ipc" and command "eth.accounts" inside quorum-examples_node1_1 container. Then downed docker-compose and upped it again but now all the accounts dismissed and not accessible right now. How should I persist in accounts?

**Comment by prd-fox** [comment]
`docker-compose` down will stop and delete the containers, so nothing is persisted. `docker-compose stop` will only stop the containers, so when you run `docker-compose up` again, the accounts will be present.

**Comment by prd-fox** [comment]
I think this issue has been addressed, if you continue to have issues with this, please re-open the ticket.

**Comment by nickmi** [comment]
I can confirm this is the case for me too
when running the following

```
docker-compose up -d
docker-compose stop
docker-compose start
```

accounts created when up are destroyed when containers are stopped 

![Screenshot_1](https://user-images.githubusercontent.com/2481323/81574430-76814f80-93ae-11ea-9382-3637740d561e.png) 

![Screenshot_2](https://user-images.githubusercontent.com/2481323/81574437-7aad6d00-93ae-11ea-8726-219749d80b07.png)
