### ISSUE TITLE
node4 can't see storedData as expected, but UNEXPECTEDLY can set the storedData that should be restricted for access

### ISSUE THREAD

**Issue by CLDH214** [jpmorganchase/quorum-examples#19]
in node 4,
```
> private.set(28,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
"0xe4622fe160ce65f39fee7c1b8c4c648cba3953b57760ba55a741192919f03cf3"
> private.get()
0
```

however in node 7,
```
> private.get()
28
```

**Comment by patrickmn** [comment]
Thanks for bringing this up. Even though the transaction contents are private, one must still guard the contracts with the typical access restrictions, e.g. "only these Ethereum accounts are allowed to do X." This is something we need to document more clearly.

In the future we'd like to add a notion of a contract being reserved only for some set of public keys and nobody else, but currently there is only a transaction-level visibility setting (privateFor) which doesn't "know" anything about contracts. I have to stress, though, that even with that kind of restriction, you'd still need to do access control inside the contract itself unless you want everyone party to it to be able to do anything.

**Comment by patrickmn** [comment]
Please feel free to submit an issue for this in the main Quorum repository to track the needed changes.

**Comment by patrickmn** [comment]
See https://github.com/jpmorganchase/quorum/issues/126

**Comment by CLDH214** [comment]
Thank you very much for being responsive!
