### ISSUE TITLE
docker-compose up -d fails

### ISSUE THREAD

**Issue by vinton-dev** [jpmorganchase/quorum-examples#192]
#### System information

OS & Version:Ubuntu 16.04

Environment: 
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89e8a
 Built:             Thu Jul 25 21:21:35 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89e8a
  Built:            Thu Jul 25 21:20:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

#### Steps to reproduce the behavior

1. docker-compose up -d

#### Error Logs
ERROR: Invalid interpolation format for "entrypoint" option in service "node1": "UDS_WAIT=10
for i in $$(seq 1 100)
do
  set -e
  if [ -S $${PRIVATE_CONFIG} ] && \
    [ "I'm up!" == "$$(wget --timeout $${UDS_WAIT} -qO- --proxy off 172.16.239.10$${NODE_ID}:9000/upcheck)" ];
  then break
  else
    echo "Sleep $${UDS_WAIT} seconds. Waiting for TxManager."
    sleep $${UDS_WAIT}
  fi
done
DDIR=/qdata/dd
rm -rf $${DDIR}
mkdir -p $${DDIR}/keystore
mkdir -p $${DDIR}/geth
cp /examples/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
cp /examples/keys/key$${NODE_ID} $${DDIR}/keystore/
cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
cat $${DDIR}/static-nodes.json
GENESIS_FILE="/examples/istanbul-genesis.json"
if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
  GENESIS_FILE="/examples/genesis.json"
fi
NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
GETH_ARGS_raft="--raft --raftport 50400"
GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
geth --datadir $${DDIR} init $${GENESIS_FILE}
geth \
  --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
  --datadir $${DDIR} \
  --permissioned \
  --nodiscover \
  --verbosity 5 \
  --networkid $${NETWORK_ID} \
  --rpc \
  --rpcaddr 0.0.0.0 \
  --rpcport 8545 \
  --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
  --port 21000 \
  --unlock 0 \
  --password /examples/passwords.txt \
  ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbu

**Comment by trung** [comment]
hi @vinton-dev, thanks for reporting the issue.

What `docker-compose` version do you use?

**Comment by Hanwang107** [comment]
Same failure! 
docker-compose version 1.17.0, build ac53b73

**Comment by Hanwang107** [comment]
@trung

**Comment by trung** [comment]
Please update your docker compose and give a try.

**Comment by vinton-dev** [comment]
@trung 
updated to docker-compose version 1.25.0-rc2, build 661ac20e
It's working fine. 

Thanks
