### ISSUE TITLE
Vagrant - 7nodes not working

### ISSUE THREAD

**Issue by khatts** [jpmorganchase/quorum-examples#195]
While running quorum/7nodes on Vagrant env.
 I get an exception -

vagrant@ubuntu-xenial:/vagrant/examples/7nodes$ ./raft-init.sh 
[*] Cleaning up temporary data directories
[*] Configuring for 7 node(s)
[*] Configuring node 1 (permissioned)
./raft-init.sh: line 64: geth: command not found

**Comment by jbhurat** [comment]
The `geth` binary is downloaded from quorum releases and copied to `/usr/local/bin` directory. Can you check if `geth` exists under that

**Comment by jbhurat** [comment]
Closing the ticket for now as there is no response or follow up comments
