### ISSUE TITLE
privateFor not working

### ISSUE THREAD

**Issue by FaziliTajamul** [jpmorganchase/quorum-examples#21]
Hi ,
Followed every step shown here https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes . 
when i execute 
private.set(4,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
 node 7 gets updated as expected .
 But when i execute private.set(4,{from:eth.coinbase,privateFor:["oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8="]}); 
to update node 4 it doesn't get updated. 
But when i try to update node 1 or node 7 from any other node both these nodes get updated. but when i try to update nodes 2-6 from any other node nothing gets updated..
Is this expected behaviour ?

**Comment by patrickmn** [comment]
The contract is only known to nodes that you put in privateFor (and your own node) for the transaction that instantiates the contract, so node 4 never saw a transaction that created the contract, and the new "set" transaction means nothing to it.

If you put all of the nodes in privateFor when you deploy the contract, then send transactions that are limited to fewer participants, you should get the behavior you want, although we recommend that you keep the recipients list constant for any given private contract.
