### ISSUE TITLE
The source of the solidity contract for the both example

### ISSUE THREAD

**Issue by jln1989** [jpmorganchase/quorum-examples#22]
Hi,
Am exploring QUORUM and am trying to find the solidity contract files which lead to the code in the genesis.json in the examples. It would be great if someone can provide me the location of it and if there is a documentation on the genesis.json as whole how each node is created and how one node is differentiated from other (voter vs creator).

**Comment by jpmsam** [comment]
@jln1989 QuorumChain has been deprecated but please refer to the [source](https://github.com/jpmorganchase/quorum/blob/q1.0.1/core/quorum/block_voting.sol) in v1 for reference.
