### ISSUE TITLE
Is 4Gb of RAM really needed to run 7Nodes?

### ISSUE THREAD

**Issue by watrindade** [jpmorganchase/quorum-examples#23]
I've just cloned the quorum-examples and I ran out of memory due to having an other virtual machine running at the time I started vagrant.

Is 4Gb of RAM really needed to run this example project?

If yes: I'm wondering of updating the README.md file with the required  VM's RAM 
If no: I thing we could decrease the memory in the Vagrantfile (v.memory = 4096) to the needed amount.

Thank you.

**Comment by jpmsam** [comment]
@watrindade this has been updated in the most recent vagrant script but you should be able to do so too.
