### ISSUE TITLE
Ensure that Quorum geth is on the PATH

### ISSUE THREAD

**Issue by lcs100** [jpmorganchase/quorum-examples#230]
#### geth version
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/home/infosec/work/env/go

#### ./raft-start.sh
ERROR: you appear to be running with upstream geth. Ensure that Quorum geth is on the PATH (before any other geth version).

#### Steps to reproduce the behavior

Hello everyone,
I am doing some experiment about quorum
But it says 
`
ERROR: you appear to be running with upstream geth. Ensure that Quorum geth is on the PATH (before any other geth version).
`
What can i do

**Comment by chris-j-h** [comment]
Hi, this message is informing you that your `geth` command is running standard go-ethereum and not quorum.  Make sure that you have [built quorum and your `PATH` variable is pointing to it](https://docs.goquorum.com/en/latest/Getting%20Started/Installing/#quorum).

To check you are using quorum, `geth version` should return something like (note the line `Quorum Version: 2.5.0`):
```shell
Geth
Version: 1.8.18-stable
Quorum Version: 2.5.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.13.7
Operating System: darwin
GOPATH=/Users/me/go
GOROOT=/usr/local/go
```

**Comment by lcs100** [comment]
Thank you. I have succeed.
