### ISSUE TITLE
Docker compose persistent data failure 

### ISSUE THREAD

**Issue by nickmi** [jpmorganchase/quorum-examples#233]
After stopping the containers  `docker-compose stop` and starting them up again 
`docker-compose start`  all the data and accounts that were created inside the quorum blockchain get deleted.  I am wondering if i have to modify the docker-compose file or if it is a bug.

Windows 10 Pro
latest quorum-examples 
latest docker Desktop

Thank you in advance

**Comment by fixanoid** [comment]
The entry point is the only place the cleanup occurs, see: https://github.com/jpmorganchase/quorum-examples/blob/64c6df5833b148e291d738838bf0fb319465ece6/docker-compose.yml#L44-L46
