### ISSUE TITLE
istanbul-init does not work for variable nodes

### ISSUE THREAD

**Issue by mamunbond07** [jpmorganchase/quorum-examples#238]
#### System information
Geth version: 1.9.7 stable

OS & Version: Ubuntu 16.04
Quorum version: 2.6

#### Expected behavior
I tried to modify the 7-nodes example in Istanbul-init.sh using the following command
> ./istanbul-init.sh --numNodes 8
#### Actual behavior
Unfortunately it does not work for 8th node. Even though my permissioned-nodes.json file contain 8 nodes information. It always shows error
>'can not stat raft/nodekey8' : no such file or directory

Why does it show this error?
Please help me to resolve this.

**Comment by SatpalSandhu61** [comment]
The `--numNodes` parameter only allows you to reduce the number of nodes (as per the [docs](https://github.com/jpmorganchase/quorum-examples#reducing-the-number-of-nodes)).

If you want to increase the number of nodes above 7 then you would need to generate extra key files yourself, and also modify the `permissioned-nodes.json` file.
The quorum-examples is capped at 7 nodes as that is sufficient to get most people up and running and experimenting with quorum. Also running more than 7 nodes on one machine is likely to exhaust your resources.

**Comment by mamunbond07** [comment]
Thanks for you reply.
The extra key files are generated using https://github.com/jpmorganchase/istanbul-tools
However, in this 7-node example, it is not explained how the extra keys are to be placed in which directories. Let's assume we need to place the keys in the keys folder. Yet, the generated keys from istanbul tools does not help in producing the contract address when the **eth.getTransactionReceipt ** is issued. Besides, the 7-node example should be able to be reconfigured about how to distributedly deploy blockchain in different nodes. Otherwise, what is the point of having blockchain in single node!
