### ISSUE TITLE
Unfortunately 7 node example is very static

### ISSUE THREAD

**Issue by mamunbond07** [jpmorganchase/quorum-examples#239]
#### Impractical example
The documentation of the 7 node example does not explain how a new node's **enode information** and **keys** can be pre-generated in order to issue the **istanbul-init.sh**. The example does not explain how to leverage the keys generated from https://github.com/jpmorganchase/istanbul-tools. This is very disappointing that the example seems very static and not re-configurable.

**Comment by fixanoid** [comment]
Hi @mamunbond07 , thanks for the feedback. As the name implies, this is meant to be a starting example to introduce basics behind Quorum blockchain and as such missing all the other vital info. However, we do have a very rich set of docs that is not missing anything. Please start here: http://docs.goquorum.com/en/latest/ and if you are specifically interested in steps required to configure and add new nodes to a net, see this: http://docs.goquorum.com/en/latest/Getting%20Started/Creating-A-Network-From-Scratch/
