### ISSUE TITLE
transaction performance

### ISSUE THREAD

**Issue by jerryhero** [jpmorganchase/quorum-examples#26]
How to test the transaction performance of 7nodes?such as how many transactions per second.

**Comment by sekharkumarroy** [comment]
Hi! Did anyone try doing any performance benchmark on the 2.0 version ? Could you please share the results ?

**Comment by jpmsam** [comment]
@jerryhero Please reference this [issue](https://github.com/jpmorganchase/quorum/issues/346)  for a discussion on TPS.

**Comment by drandreaskrueger** [comment]
@jerryhero & @sekharkumarroy - hey!  
Yes, great - please help with this endeavor.  
My time given to work on this is pretty limited, so I won't be doing large steps.

Also: Where to place this better? Closed github issues might not be the best place ...
