### ISSUE TITLE
Fatal: invalid genesis file: missing 0x prefix for hex data

### ISSUE THREAD

**Issue by tomachinz** [jpmorganchase/quorum-examples#28]
This is a fresh install... do I need to install/start geth on my Ubuntu instance? I'm running Mac OS.

13inch:7nodes tom$ pwd
/Users/tom/GitHub/quorum-examples/examples/7nodes
13inch:7nodes tom$ ls
README.md		raft			stop.sh
bench-private-async.sh	raft-init.sh		tm1.conf
bench-private-sync.sh	raft-start.sh		tm2.conf
bench-public-sync.sh	runscript.sh		tm3.conf
genesis.json		script1.js		tm4.conf
init.sh			send-private-async.lua	tm5.conf
keys			send-private-sync.lua	tm6.conf
passwords.txt		send-public-sync.lua	tm7.conf
qdata			start.sh
13inch:7nodes tom$ ./init.sh
[*] Cleaning up temporary data directories
[*] Configuring node 1
Fatal: invalid genesis file: missing 0x prefix for hex data
13inch:7nodes tom$

**Comment by tomachinz** [comment]
SOLVED: I was not running inside the vagrant enviro - I was trying to run on my host Mac. 
SOLUTION: run vagrant ssh to get into the vm and try again from ubuntu@ubuntu-xenial:~/quorum-examples/7nodes$

**Comment by tylobban** [comment]
Will make the docs clearer, thanks!
