### ISSUE TITLE
newer constellation doesn't work with the 7nodes example

### ISSUE THREAD

**Issue by martyall1** [jpmorganchase/quorum-examples#33]
I'm trying to figure out how to run the 7nodes example with a new constellation release 0.1.0 and it seems that the existing configuration files break the example, as well as my best guess at changing the config files to the new format.

With the existing config files, the node crashes with an error message like
`"encrypt: Sender cannot be a recipient"`, and with the new ones I get something like
```
Errors while running sendPayload: [Left "Unknown recipient\nCallStack (from HasCallStack):\n  error, called at ./Constellation/Node.hs:157:21 in constellation-0.1.0.0-6e8lqFuBPtzCz3iEft1Zk0:Constellation.Node"]
```

here's what I'm using for the config file for node 1 for example

```
url = "http://127.0.0.1:9001/"
port = 9001
socket = "qdata/tm1.ipc"
othernodes = []
publickeys = ["keys/tm1.pub"]
privatekeys = ["keys/tm1.key"]
alwayssendto = []
storage = "qdata/constellation1"
verbosity = 3

```

I'm not really sure what I'm doing wrong, any comments would help.

**Comment by patrickmn** [comment]
I can't reproduce this. Works as expected with both the new and old configuration format.

Could you provide a reproducible example?

**Comment by RaziAbbas** [comment]
Getting similar error - Here is the test code - from QuorumIT - in webj/test package. 


[QuorumIT-java.txt](https://github.com/jpmorganchase/quorum-examples/files/1631770/QuorumIT-java.txt)

**Comment by jpmsam** [comment]
@RaziAbbas Please test the latest updates as we introduced a few fixes.
