### ISSUE TITLE
init.sh : command not found

### ISSUE THREAD

**Issue by lugyin** [jpmorganchase/quorum-examples#34]
Situation:
I'm running through the tutorial and have successfully ssh into...
ubuntu@ubuntu-xenial:~/quorum-examples/7nodes$

I'm trying to execute init.sh and start.sh

looking at list files, I see both init.sh and start.sh available in 7nodes
![screen shot 2017-08-11 at 3 46 57 pm](https://user-images.githubusercontent.com/8801819/29234515-592737c0-7eac-11e7-8183-62ffbc8e8d5b.png)

Expected Behavior:
I expected to have the 7 nodes up and running.

Actual Behavior:

instead I received...
"ubuntu@ubuntu-xenial:~/quorum-examples/7nodes$ init.sh
init.sh: command not found"

**Comment by patrickmn** [comment]
Try `./init.sh` and `./start.sh`
