### ISSUE TITLE
raftport querystring missing when running raft 7 nodes example

### ISSUE THREAD

**Issue by charlescrain** [jpmorganchase/quorum-examples#40]
Hi,

When running `./raft-init.sh`, then `./raft-start.sh` the nodes fail to startup due to this error: 
```
Fatal: raftport querystring parameter not specified in static-node enode ID: enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@127.0.0.1:21000?discport=0. please check your static-nodes.json file.
```

From the raft docs, it looks like the `static-nodes.json` file is missing the `raftport` query string mentioned here https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md#initial-configuration-and-enacting-membership-changes. Could I be running the script incorrectly and it handles adding the raftport somewhere else?

-Charles

**Comment by charlescrain** [comment]
Just adding raftport querystring to enode addresses causes the first node to work, but it doesn't use the specified `raftport` in the query string instead using `50400`. I was able to track down why this happens, the missing `--raftport` cli parameter when starting up the raft nodes in `raft-start.sh`. Going to leave this open until this has been implemented.

**Comment by jpmsam** [comment]
@charlescrain this has been fixed in the raft-start.sh script.
