### ISSUE TITLE
Where are the private keys for 7 nodes kept? 

### ISSUE THREAD

**Issue by simonmullaney** [jpmorganchase/quorum-examples#42]

**Comment by patrickmn** [comment]
https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes/keys `key*` (geth accounts) and `*.key` (Constellation)

**Comment by simonmullaney** [comment]
I still can't find the private keys in here, for example in key1 (below) I cant see the private key... 

{"address":"ed9d02e382b34818e88b88a309c7fe71e65f419d","crypto":{"cipher":"aes-128-ctr","ciphertext":"4e77046ba3f699e744acb4a89c36a3ea1158a1bd90a076d36675f4c883864377","cipherparams":{"iv":"a8932af2a3c0225ee8e872bc0e462c11"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"8ca49552b3e92f79c51f2cd3d38dfc723412c212e702bd337a3724e8937aff0f"},"mac":"6d1354fef5aa0418389b1a5d1f5ee0050d7273292a1171c51fd02f9ecff55264"},"id":"a65d1ac3-db7e-445d-a1cc-b6c5eeaa05e0","version":3}

**Comment by patrickmn** [comment]
That's because it's a locked account. The ciphertext is the private key encrypted with a key derived from the lock password.

Constellation keys have the same concept, although the ones in the example aren't locked.

Out of curiosity, what do you need the private key for?

**Comment by simonmullaney** [comment]
I have a web app built with webpack which is pointed at the quorum 7 nodes. I want to be able to interact with the web app with different accounts. To do this I have configured MetaMask to point to localhost:22000 (node 1) but in order to add accounts to metamask you need their private key. Do you know where to find the encryption password so that I can decrypt the private key from the keyfile?
