### ISSUE TITLE
New node to join the network

### ISSUE THREAD

**Issue by alexpee** [jpmorganchase/quorum-examples#43]
Hi I understand that we have to define the all the the makers, voters node in the storage section of the genesis json file.

Is it possible to create a new and late coming node and join an existing quorum network that is actively running and was previously initialized based on the genesis json file which doesn't contain the storage info of the new node?

Thank you.

**Comment by jpmsam** [comment]
@alexpee that was possible in QuorumChain. Please note that it has been replaced with Istanbul BFT in Quorum v2.
