### ISSUE TITLE
files not copied to the vagrant box with latest master (commit: f3ddbae74ef987251f34662c0c0a4c2e0c3cd2f1)

### ISSUE THREAD

**Issue by CLDH214** [jpmorganchase/quorum-examples#44]
after ```vagrant up && vagrant ssh```, ls will display nothing like the quorum-examples folder

**Comment by songzy12** [comment]
Same here. When I run `vagrant up`, it will display error message:
```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jpmsam** [comment]
@CLDH214 That means vagrant failed to pull in all the required dependancies. Doing `vagrant destroy` and `vagrant up` should solve that.
