### ISSUE TITLE
Generating keys for Quorum nodes

### ISSUE THREAD

**Issue by sahar-fehri** [jpmorganchase/quorum-examples#48]
Hello guys ,
Im trying to build a quorum network from scratch, and im trying to get inspired by the 7 nodes example of quorum-examples.

Here is what i did : 
I used the Quorum-Genesis utility in order to create the genesis file. Then i have set up my bootnode and saved its key and enode address to use it later when starting my nodes .

Then i wanted to make an init.sh and start.sh scripts similar to those in the 7 nodes example in order to make it easier to start my network. However i found some issues. 

In the 7 nodes example there is a folder called "keys" which contains the UTC files for all the accounts specified in the genesis.json file also it has the public keys,private keys  and archival keys to start constellations . I don't understand how am i supposed to generate all those keys???? and obviously i need those public keys and archival keys in order to populate the "tm.conf" files so i can start my constellations later by doing : 
constellation-node tm.conf. 

If anyone could clarify this for me i would really appreciate it,
 thank you .

**Comment by patrickmn** [comment]
The command to generate constellation key pairs is `constellation-node --generatekeys=foo` (will create `foo.pub` and `foo.key`).
