### ISSUE TITLE
How to do Send Transaction from account A to B on quorum

### ISSUE THREAD

**Issue by anupamj** [jpmorganchase/quorum-examples#51]
Hi Team 

I have done the private setup of a raft based quorum. The example is working properly. 
But when I try to do coin transfer from one  account to another then I am seeing the below error in the log. Its a fresh setup and no mining has been done. But still seeing the mining error. 

> eth.sendTransaction({from:web3.eth.accounts[0], to: web3.eth.accounts[1], privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="], value: "1" });
Error: Post http+unix://c/send: dial unix qdata/tm1.ipc: connect: connection refused
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

ubuntu@blockchain03:~/quorum-examples$ tail qdata/logs/7.log
INFO [11-23|12:26:54] 🔨  Mined block                           number=1 hash=b2b24061      elapsed=7.067924ms
INFO [11-23|12:26:54] QUORUM-CHECKPOINT                        name=TX-ACCEPTED   tx=0xd51abe3f6e5fa272aa6158d08c783191c19504d345374b0369d389504f164a8b
INFO [11-23|12:26:54] QUORUM-CHECKPOINT                        name=BLOCK-CREATED block=b2b240612fe20e580500c1f6f9949fe6bcf8ce133be7c44cd3a568fa6ee7dbb7
INFO [11-23|12:26:54] persisted the latest applied index       index=9
INFO [11-23|12:38:55] Generated next block                     block num=2 num txes=1
INFO [11-23|12:38:55] 🔨  Mined block                           number=2 hash=7610b91a      elapsed=2.865896ms
INFO [11-23|12:38:55] Non-extending block                      block=7610b9…99cfb0                                                    parent=b2b240…e7dbb7 head=62c2c0…5a3c94
INFO [11-23|12:38:55] persisted the latest applied index       index=10
INFO [11-23|12:38:55] Handling InvalidRaftOrdering             invalid block=7610b9…99cfb0 current head=62c2c0…5a3c94
INFO [11-23|12:38:55] Someone else mined invalid block; ignoring block=7610b9…99cfb0

Our intention to do a simple payment from account A to account B. When I dont specify the privateFor the transaction successfully gets submitted but doesnot get succeeded. It awaits in the pending queue. 

> eth.sendTransaction({from:eth.accounts[0], to:eth.accounts[1], value:1})
"0x00cd1f4ea060c53aa1edacbcd11c3b4f9c32a9e04cf545018de02518e35c18cb"
> txpool.inspect.pending
{
  0x0638E1574728b6D862dd5d3A3E0942c3be47D996: {
    0: "contract creation: 0 wei + 4700000 × 0 gas"
  },
  0x9186eb3d20Cbd1F5f992a950d808C4495153ABd5: {
    0: "contract creation: 0 wei + 4700000 × 0 gas"
  },
  0xcA843569e3427144cEad5e4d5999a3D0cCF92B8e: {
    0: "contract creation: 0 wei + 4700000 × 0 gas",
    1: "0x2C80Eba934Fa0deE778FD0029bcD77A2cD31959e: 10000000000000000000000000 wei + 90000 × 0 gas",
    2: "0x0fBDc686b912d7722dc86510934589E0AAf3b55A: 1 wei + 90000 × 0 gas",
    3: "0x0fBDc686b912d7722dc86510934589E0AAf3b55A: 1 wei + 90000 × 0 gas"
  },
  0xed9d02e382b34818e88B88a309c7fe71E65f419d: {
    0: "contract creation: 0 wei + 4700000 × 0 gas",
    1: "contract creation: 0 wei + 4700000 × 0 gas",
    2: "contract creation: 1 wei + 90000 × 0 gas",
    3: "contract creation: 1 wei + 90000 × 0 gas"
  }
}

**Comment by mkqaimari** [comment]
I'm trying the same scenario:

The tx object I'm using is: 

const o = {
    "from": web3.eth.defaultAccount,
    "to": web3.eth.defaultAccount,
    "value": "0x0",
    "privateFor": ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]
};

and I'm receiving the same error:

error, result Error: Post http+unix://c/send: dial unix qdata/tm1.ipc: connect: connection refused
    at Object.InvalidResponse (/Users/mac/Desktop/Quorum/web3/node_modules/web3quorum/lib/web3/errors.js:38:16)
    at /Users/mac/Desktop/Quorum/web3/node_modules/web3quorum/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/Users/mac/Desktop/Quorum/web3/node_modules/web3quorum/lib/web3/httpprovider.js:122:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12) undefined

**Comment by DavidBelinchon** [comment]
Private transactions can be made between nodes, not accounts,

It's related [here](https://github.com/jpmorganchase/quorum-examples/issues/12)

**Comment by jpmsam** [comment]
@anupamj @mkqaimari private transactions aren't supported for ether value transfers. The balance for all accounts must be public for the transaction to be validated by all the nodes on the network.
