### ISSUE TITLE
making a permissioned network with raft

### ISSUE THREAD

**Issue by sahar-fehri** [jpmorganchase/quorum-examples#53]
Hello guys,
Im working on the 7nodes example and i have started the cluster using raft consensus. And then i tried to make a permissioned network consisting of 3 nodes, following the steps mentioned in the wiki but it's not working . and i'm starting to wonder maybe it's not possible to make a permissioned network if you are using Raft ????

Thank you,

**Comment by ksbachu** [comment]
Please follow below repo. It is awesome.
https://github.com/Szkered/quorum-raft-cluster

**Comment by jpmsam** [comment]
@sahar-fehri please follow the latest example.
