### ISSUE TITLE
What happens when bootnode goes down ?

### ISSUE THREAD

**Issue by sivachaitanya** [jpmorganchase/quorum-examples#54]
So I have setup 2 nodes, 1 on Azure and 1 on AWS and was able to successfully sync the data between them. In the node 1 is started as single block maker and boot node, and node 2 as voter. Later I added node 2 as block maker using the 0x20 with the permission of node 1, so this is as contract level. Now what happens when node 1 gone down, can I still publish my Tx to node 2 which was blockmaker assigned by node 1 ? or in this case can I define node 2 as boot node as well ?

**Comment by patrickmn** [comment]
bootnode is no longer used in favor of static-nodes.json
