### ISSUE TITLE
How to generate permission-nodes.json?

### ISSUE THREAD

**Issue by Lisprez** [jpmorganchase/quorum-examples#59]
I have not found the way to generate the file permission-nodes.json
It is just give in the 7nodes example

**Comment by ssudhir123** [comment]
The "permissioned-nodes.json" follows the same pattern as "static-nodes.json". You should be able to use your favorite text editor and list the "enode://pubkey@ip:port" combinations in well formatted JSON file.  Further details here:
https://github.com/jpmorganchase/quorum/wiki/Security
