### ISSUE TITLE
Contract deplyment transaction excuting successfully but no contract deployed...

### ISSUE THREAD

**Issue by Rakhisb** [jpmorganchase/quorum-examples#60]
quorum -version: v2.0.0
consensus: raft

we have done four node setup, node1 showing up as a minter and other as verifiers.
when we are trying to deploy 7 nodes example contract from node1. It returns transaction receipt as bellow

> eth.getTransactionReceipt("0xab500348ffc57f231d9569064f6da7a5b3912ace829070862d15e1273fbb265f")
{
  blockHash: "0x8b31dc8a9074909c228867b3bed240df5b33963ba95dd392caff3f46d316493c",
  blockNumber: 12,
  contractAddress: "0x3f7cb7b26dad554cde28e4933b8e4861137dd081",
  cumulativeGasUsed: 90000,
  from: "0x2ac8e4d477bf82e3988f8b1d1071b6e275483dfe",
  gasUsed: 90000,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  root: "0x0ec0ef674a4436bd4509ea8f50c3fe89cc82f21bcb0e82a4679e11023fd304dc",
  to: null,
  transactionHash: "0xab500348ffc57f231d9569064f6da7a5b3912ace829070862d15e1273fbb265f",
  transactionIndex: 0
}

but getCode is returns null means contract is not deployed.
> eth.getCode("0x3f7cb7b26dad554cde28e4933b8e4861137dd081")
"0x"

could you help us understand this behavior?

**Comment by jpmsam** [comment]
@Rakhisb Can you please provide more details on how you deployed the contract? Also, please update to the most recent release as we have fixed some related issues.

**Comment by jpmsam** [comment]
@Rakhisb please reopen if this is still an issue after the upgrade.
