### ISSUE TITLE
key copying errors in raft-init.sh and istanbul-init.sh

### ISSUE THREAD

**Issue by didil** [jpmorganchase/quorum-examples#62]
those file contain the lines:

````
cp keys/key2 qdata/dd2/keystore
cp keys/key3 qdata/dd2/keystore
````

so the key for node 2 is overwritten and replace by node 3's key, then below in the files there is no code to copy node 3's  key to the proper folder

**Comment by jpmsam** [comment]
@didil  We'll be fixing this as part of Pull Request #88
