### ISSUE TITLE
Vagrant error

### ISSUE THREAD

**Issue by colinator** [jpmorganchase/quorum-examples#65]
Running vagrant up yields an error:

```
    default: chown: cannot access '/home/ubuntu/quorum'
    default: : No such file or directory
```

... probably because quorum wasn't installed in /home/ubuntu, it was installed in /home/vagrant.

When vagrant up is run, it does this:
```
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```
.. which means it logs in as 'vagrant', right? So then later it does git clone <quorum>, it installs that in /home/vagrant, NOT /home/ubuntu, which means the chown will fail, right? Am I missing something? How does this work for anyone? Furthermore, then when doing vagrant ssh in to the virtual box, the directions just say to cd to the examples directly, but that's been copied to ubuntu. Am I missing directions for how to actually ssh in to the virtual box as ubuntu?

**Comment by DavidBelinchon** [comment]
I'm just changed this 2 lines(in file /vagrant/bootstrap.sh):
```
cp -r /vagrant/examples /home/vagrant/quorum-examples
chown -R vagrant:vagrant /home/vagrant/quorum /home/vagrant/quorum-examples
```
and then everything works well

**Comment by colinator** [comment]
I agree with the first line. But since the script is executing as vagrant already, it shouldn't need to chown, right? I did the same thing (the cp, no chown, and stuff works, as far as I can tell).

**Comment by DavidBelinchon** [comment]
Yes, without the last line everything should be works, 
but with last line you no need type sudo

**Comment by patrickmn** [comment]
Based on your descriptions, I guess they changed the default user from `ubuntu` to `vagrant` in newer versions of this box. Strange.

**Comment by porteron** [comment]
Having the same issue:
` default: chown: cannot access '/home/ubuntu/quorum'`

Temp fix: 
After you run `vagrant ssh` and are in the vm, run a git clone of the quorum repo. Then navigate to the new repo and the examples for 7nodes is in there.

**Comment by patrickmn** [comment]
This should now be fixed.

**Comment by preeti13456** [comment]
didn't get this sorted this is the error I am facing , vagrant@ubuntu-xenial:~$ cd quorum-examples
-bash: cd: quorum-examples: No such file or directory
