### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by araskachoi** [jpmorganchase/quorum-examples#67]
When running  `./raft-init.sh` on vagrant, I get a long list of "permission denied"... I've listed the code below:

>> vagrant@ubuntu-xenial:~/quorum-examples/7nodes$ ./raft-init.sh
[*] Cleaning up temporary data directories
rm: cannot remove 'qdata/constellation5/payloads': Permission denied
rm: cannot remove 'qdata/constellation7/payloads': Permission denied
rm: cannot remove 'qdata/dd5/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd5/keystore/key5': Permission denied
rm: cannot remove 'qdata/dd5/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd5/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd5/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd5/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd5/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd5/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd5/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd5/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd5/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd5/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd5/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/constellation6/payloads': Permission denied
rm: cannot remove 'qdata/constellation2/payloads': Permission denied
rm: cannot remove 'qdata/dd3/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd3/keystore': Permission denied
rm: cannot remove 'qdata/dd3/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd3/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd3/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd3/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd3/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd3/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd3/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd3/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd3/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd3/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd3/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd3/permissioned-nodes.json': Permission denied
rm: cannot remove 'qdata/dd6/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd6/keystore': Permission denied
rm: cannot remove 'qdata/dd6/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd6/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd6/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd6/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd6/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd6/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd6/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd6/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd6/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd6/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd6/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd1/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd1/keystore/key1': Permission denied
rm: cannot remove 'qdata/dd1/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd1/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd1/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd1/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd1/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd1/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd1/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd1/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd1/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd1/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd1/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd1/permissioned-nodes.json': Permission denied
rm: cannot remove 'qdata/dd2/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd2/keystore/key3': Permission denied
rm: cannot remove 'qdata/dd2/keystore/key2': Permission denied
rm: cannot remove 'qdata/dd2/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd2/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd2/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd2/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd2/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd2/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd2/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd2/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd2/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd2/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd2/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd2/permissioned-nodes.json': Permission denied
rm: cannot remove 'qdata/constellation1/payloads': Permission denied
rm: cannot remove 'qdata/constellation3/payloads': Permission denied
rm: cannot remove 'qdata/dd4/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd4/keystore/key4': Permission denied
rm: cannot remove 'qdata/dd4/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd4/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd4/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd4/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd4/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd4/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd4/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd4/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd4/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd4/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd4/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd4/permissioned-nodes.json': Permission denied
rm: cannot remove 'qdata/logs/constellation1.log': Permission denied
rm: cannot remove 'qdata/logs/4.log': Permission denied
rm: cannot remove 'qdata/logs/5.log': Permission denied
rm: cannot remove 'qdata/logs/constellation6.log': Permission denied
rm: cannot remove 'qdata/logs/2.log': Permission denied
rm: cannot remove 'qdata/logs/7.log': Permission denied
rm: cannot remove 'qdata/logs/3.log': Permission denied
rm: cannot remove 'qdata/logs/constellation3.log': Permission denied
rm: cannot remove 'qdata/logs/constellation7.log': Permission denied
rm: cannot remove 'qdata/logs/constellation5.log': Permission denied
rm: cannot remove 'qdata/logs/6.log': Permission denied
rm: cannot remove 'qdata/logs/1.log': Permission denied
rm: cannot remove 'qdata/logs/constellation4.log': Permission denied
rm: cannot remove 'qdata/logs/constellation2.log': Permission denied
rm: cannot remove 'qdata/dd7/static-nodes.json': Permission denied
rm: cannot remove 'qdata/dd7/keystore': Permission denied
rm: cannot remove 'qdata/dd7/geth/nodekey': Permission denied
rm: cannot remove 'qdata/dd7/geth/chaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd7/geth/chaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd7/geth/chaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd7/geth/chaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd7/geth/chaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/dd7/geth/lightchaindata/LOG': Permission denied
rm: cannot remove 'qdata/dd7/geth/lightchaindata/CURRENT': Permission denied
rm: cannot remove 'qdata/dd7/geth/lightchaindata/LOCK': Permission denied
rm: cannot remove 'qdata/dd7/geth/lightchaindata/000001.log': Permission denied
rm: cannot remove 'qdata/dd7/geth/lightchaindata/MANIFEST-000000': Permission denied
rm: cannot remove 'qdata/constellation4/payloads': Permission denied

Any tips on how to get "permission" to move forward?

Thanks in advance!

**Comment by patrickmn** [comment]
please try to `sudo rm -rf qdata` then re-run `./raft-init.sh`

**Comment by araskachoi** [comment]
@patrickmn still getting "Permission denied" ):

[*] Cleaning up temporary data directories
mkdir: cannot create directory ‘qdata’: Permission denied

**Comment by patrickmn** [comment]
does `sudo chown -R vagrant:vagrant ~/quorum-examples` help?

**Comment by araskachoi** [comment]
I added that to my `bootstrap.sh` file and i'm getting:

```
vagrant@ubuntu-xenial:~/quorum-examples/7nodes$ ./raft-init.sh
[*] Cleaning up temporary data directories
mkdir: cannot create directory ‘qdata’: Permission denied
```

**Comment by araskachoi** [comment]
@patrickmn 
I inputted it into my terminal and it seemed to work. Thanks!
