### ISSUE TITLE
What determines the roles of nodes in 7 nodes raft example?

### ISSUE THREAD

**Issue by mohdrashid** [jpmorganchase/quorum-examples#70]
Could someone help me understand how the roles of nodes are classified as block-maker, voter or observer in the raft aspect of 7-nodes examples. The genesis files does not have any reference to the address or is it pre-assigned somehow?

**Comment by DavidBelinchon** [comment]
You seem to be confusing the QuorumChain consensus mechanism (which has BlockVoters and BlockMakers) with the raft consensus mechanism.
* QuorumChain: https://github.com/jpmorganchase/quorum/wiki/QuorumChain-Consensus (removed at quorum 2.0)
* Raft: https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md
