### ISSUE TITLE
Running raft-start.sh doesn't create geth.ipc

### ISSUE THREAD

**Issue by prashantprabhakar** [jpmorganchase/quorum-examples#71]
I was following the [5nodesRTGS](https://github.com/bacen/quorum-examples/tree/master/examples/5nodesRTGS) example for Quorum.
Steps performed:

- Clone the repo : https://github.com/bacen/quorum-examples.git
- cd quorum-examples/examples/5nodesRTGS
- sudo ./bootstrap.sh (this installs Constellation, GO and Quorum)
- I run : sudo ./raft-init.sh

> INFO [01-31|15:23:00] Successfully wrote genesis state         database=lightchaindata                                                                                                       hash=c23b4e…8b1b71

- Next I run: sudo ./raft-start.sh

> [*] Starting Constellation nodes
> [*] Starting node 1 - Bank 1
> [*] Starting node 2 - Bank 2
> [*] Starting node 3 - Bank 3
> [*] Starting node 4 - Regulator
> [*] Starting node 5 - Observer
> [*] Waiting for nodes to start
> 
>  All nodes configured. See 'qdata/logs' for logs, and run e.g. 'geth attach qdata/dd4/geth.ipc' to attach to the RTGS Regulator Geth node

-  geth attach ipc:qdata/dd1/geth.ipc

> Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory

This is where i get the error. After running raft-start.sh , if I check qdata/dd1, it has no geth.ipc generated.

**Comment by Amitkr1787** [comment]
Hello Prabhakar,
It seems the issue with tm.conf file configuration in 7nodes folder.
make sure the keys like socketpath, url and other are present. 
please check the logs for detail description of the issue.

Thanks & Regards,
Amit Kumar

**Comment by patrickmn** [comment]
Does this occur in the latest jpmorganchase/quorum-examples vagrant image?
