### ISSUE TITLE
vagrant up failing on OSX VBox 5.6.2

### ISSUE THREAD

**Issue by jrgleason** [jpmorganchase/quorum-examples#72]
I am trying to run `vagrant up` it gets through most of it, however, later in the script it throws an error and exits...

```
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm1.ipc' for reading: Operation not supported
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm2.ipc' for reading: Operation not supported
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm3.ipc' for reading: Operation not supported
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm7.ipc' for reading: Operation not supported
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm6.ipc' for reading: Operation not supported
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm4.ipc' for reading: Operation not supported
    default: cp: cannot open '/vagrant/examples/7nodes/qdata/tm5.ipc' for reading: Operation not supported
```

**Comment by jrgleason** [comment]
Looks like a restart fixed it for some reason. I also tried chmoding the files to add r for everyone but that didn't fix it till I restarted so it could have been either or both.

**Comment by jrgleason** [comment]
NM When I sshed no examples folder and when I destroyed and tried to recreate the vagrant image I get the failure again.

**Comment by patrickmn** [comment]
This is due to the new vagrant box changing the user from `ubuntu` to `vagrant`. The issue should be fixed in the latest quorum-examples master commit.
