### ISSUE TITLE
bitrot in the documentation?

### ISSUE THREAD

**Issue by fdouglis** [jpmorganchase/quorum-examples#74]
I only recently learned of quorum and deployed it with quorum-examples on virtualbox & vagrant.  I hit some gotchas trying to reconcile the documentation to reality.  These include:

- `raft-start.sh` is supposed to send an initial transaction, according to `README`,  but the last line of it echoes a command to invoke something else to send that transaction.  That's easily missed.  In addition, the command it says to run is `runscript` while the file is `runscript.sh`.  
- The log doesn't seem to have the address, despite 'README` saying 

> The address can be found in the node 1's log file 7nodes/qdata/logs/1.log, or alternatively by reading the contractAddress param after calling eth.getTransactionReceipt(txHash)

If in fact the address is there, please be clearer how to find it.  The only address I found was of the wallet, but I don't think that's what you meant.
- Finally, I didn't actually get the demo to progress as expected.  When I opened the console on 1, 4, and 7, and I updated the address to reflect the new transaction I created manually with `runscript.sh`, I showed a balance of 42 on node 1 (correct), 0 on  node 4 (correct, but you can't tell the difference between this and having a bad address), and 0 on node 7 (incorrect).

**Comment by NicolasMassart** [comment]
I noticed the same things.
I also noticed an error in all log files is inserted when trying to run the set command (except node 1 log as I run the command on this node) : 
> 2018 Feb-14 20:24:53688008 [WARN] Failed to decode '/receiveraw' (GET) request: Error in $: not enough input

**Comment by RobTS** [comment]
Same here, where can I find the transaction address/how can I trigger the transaction? ```./runscript.sh script1.js``` seems to get a 500 response in my case.

**Comment by RobTS** [comment]
Well, after deleting the project and starting from scratch, it suddenly worked. So feel free to try that as well. Here's what I did:

```
git clone git@github.com:jpmorganchase/quorum-examples.git
cd quorum-examples
vagrant up
vagrant ssh
```

```
cd quorum-examples/7nodes
./raft-init.sh
./raft-start.sh
./runscript.sh script1.js
```

**Comment by jpmsam** [comment]
@fdouglis we updated the typo in the startup scripts. We'll also be updating the documentation to match the most recent script changes for running the sample contract.
