### ISSUE TITLE
7-nodes-example: raft-start.sh: PRIVATE_CONFIG pointing to ipc files

### ISSUE THREAD

**Issue by kekomal** [jpmorganchase/quorum-examples#75]
In the last commit of raft-start.sh, PRIVATE_CONFIG points to ipc sockets instead of conf files. Is it OK?

**Comment by patrickmn** [comment]
I recently updated Quorum to support both config files and IPC sockets (so you don't have to make a configuration file for Constellation / can just use command-line parameters): https://github.com/jpmorganchase/quorum/commit/2a5a1d6146e38b7025868ad0cfa183f42de3554e

As long as you're running the latest Constellation and Quorum binaries, it should work. Please let me know if it does not.

**Comment by kekomal** [comment]
OK, thanks.

I'm currently working with Constellation 0.1.0 (which seems to be much more stable in my environment than 0.2.0), so I'll play with the previous branch of these examples.
