### ISSUE TITLE
Code stays in infinite loop

### ISSUE THREAD

**Issue by HimanshuK18** [jpmorganchase/quorum-examples#76]
the below code in the file constellation-start.sh never exits as all the 7 conditions are never true.

```
while $DOWN; do
    sleep 0.1
    DOWN=false
    for i in {1..7}
    do
	if [ ! -S "qdata/c$i/tm.ipc" ]; then
            DOWN=true
	fi
    done
done
```

**Comment by jiaochangyang** [comment]
Did you us vagrant to set up the examples or did you do it yourself? Check the logs for a constellation node to see what is wrong (examples/7nodes/qdata/logs). My problem was that my constellation was not up to date.

**Comment by HimanshuK18** [comment]
Well i am using the example on Ubuntu server, as quorum 2.0 does not support quorumchain and start.sh is actually a quorumchain example, so that could be a reason it got struck.

**Comment by jiaochangyang** [comment]
You should try using raft-start.sh and see what happens

**Comment by HimanshuK18** [comment]
Done that also and it has another set of issues. I have quorum 7 nodes example running on a ubuntu system, with RAFT consensus, it works all good till it reaches block number 2656 and after that it just stops mining or doing any contract updates. I am also facing the same issue on a second ubuntu server. Is there a bug in the latest code ?

**Comment by jpmsam** [comment]
@HimanshuK18 Please update to the most recent version of Quorum master, we did a fix for the block number limit.
