### ISSUE TITLE
Vagrant up issue 

### ISSUE THREAD

**Issue by deepskandpal** [jpmorganchase/quorum-examples#77]
Hi,
I m trying to use Quorum on my PC (Ubuntu 16.04 ) Vagrant version 2.0.2 Virtual box version [5.2.6]
![vagrant](https://user-images.githubusercontent.com/10810284/36245047-14ee562e-124f-11e8-910d-1d1daf35a290.png)

Can you direct me to a fix 
I forgot to mention. I m currently running Ubuntu as a virtual machine and I got to know about nested virtualization if anyone can help me figure about nested virtualization ( the host machine is windows 10)

**Comment by alberto-hernandez** [comment]
You need to enable the Virtualization (VT-X) in your BIOS.
This is not a Quorum problem, is a configuration in your machine to be able to execute VirtualBox machines (Search for "Enable VTX" on google).
