### ISSUE TITLE
Smart Contract privateFor issue: private.get() = 42 for all nodes

### ISSUE THREAD

**Issue by MikeTD** [jpmorganchase/quorum-examples#80]
This is a question for the experts.

I am having an issue with the 7Nodes example to test the privacy across a Quorum network which I can't debug.

After implementing the smart contract script1.js, Nodes 1 and 5 both return private.get() = 42. Great success!

The problem is that all other Nodes also return > private.get() = 42, when the expected value = 0.

Note also that after updating the smart contract to value = 4 in Node 1
> private.set(4,{from:eth.coinbase,privateFor:["R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY="]});

All nodes return the updated value.
> private.get() = 4 for all nodes

I’ve been over my scripts in detail but I can’t understand why the smart contract details are not restricted to nodes 1 & 5.

Have attached a copy of script1.js and the code implementation in Node 2.

**script1.js**
a = eth.accounts[0]
web3.eth.defaultAccount = a;
// abi and bytecode generated from simplestorage.sol:
// > solcjs --bin --abi simplestorage.sol
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"type":"constructor"}];
var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";
var simpleContract = web3.eth.contract(abi);
var simple = simpleContract.new(42, {from:web3.eth.accounts[0], data: bytecode, gas: 0x47b760, privateFor: ["R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY="]}, function(e, contract) {
	if (e) {
		console.log("err creating contract", e);
	} else {
		if (!contract.address) {
			console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
		} else {
			console.log("Contract mined! Address: " + contract.address);
			console.log(contract);
		}
	}
});

**Code Implementation in Node2**
mike@mike-vm:~/Blockchain/Quorum/quorum-examples/examples/7nodes$ geth attach qdata/dd2/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9
coinbase: 0xca843569e3427144cead5e4d5999a3d0ccf92b8e
at block: 8 (Tue, 13 Feb 2018 22:37:18 GMT)
datadir: /home/mike/Blockchain/Quorum/quorum-examples/examples/7nodes/qdata/dd2
modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> txHash = "0x00b96446a4f32c677fe8901b4f3bdc261ac0d831bc1c17d38163851d63110efa"
"0x00b96446a4f32c677fe8901b4f3bdc261ac0d831bc1c17d38163851d63110efa"

> eth.getTransactionReceipt(txHash)
{
  blockHash: "0x6a7330544ae5469a3194d476f458941c22bd73dca105a8482c0a1d02713a1928",
  blockNumber: 3,
  contractAddress: "0x1932c48b2bf8102ba33b4a6b545c32236e342f34",
  cumulativeGasUsed: 144806,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gasUsed: 144806,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  root: "0xbf77c1ea394bd4e73efbd97afb3d2ec54b4205215a44b1b2e4f57d50aaff1bdf",
  to: null,
  transactionHash: "0x00b96446a4f32c677fe8901b4f3bdc261ac0d831bc1c17d38163851d63110efa",
  transactionIndex: 0
}

> var address = "0x1932c48b2bf8102ba33b4a6b545c32236e342f34"
undefined

> var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
undefined

> var private = eth.contract(abi).at(address)
undefined

> private.get()
42

**Comment by jpmsam** [comment]
@MikeTD  Can you please confirm that you hadn't shared the constellation keys across all the nodes? Those would be the tm*.(pub|key).

**Comment by jpmsam** [comment]
Please reopen if this is still an issue.
