### ISSUE TITLE
Copying Constellation public and private keys

### ISSUE THREAD

**Issue by SebLKMa** [jpmorganchase/quorum-examples#81]
I have a question if having both public and private keys is enough for a node to access private contract,
(even when both the keys initially belong to another node) e.g. is below steps by Design ?

I started constellation-nodes and geth nodes 1 to 5 only.
I did not start constellation and geth nodes 6 and 7.
Before starting constellation-node 6, I copied node7's tm.pub and tm.key over to node6, see here:
...@ubuntu:~/dev/quorum-examples/examples/7nodes_v1$ more qdata/c6/tm.pub
ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=

I then start constellation 6 and geth node 6.
Geth node 1 can still send contract privateFor "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=" (which this pub key originally belongs to constellation node 7)

From geth node 6, see enode and contract access
> admin.nodeInfo
{
  enode: "enode://eacaa74c4b0e7a9e12d2fe5fee6595eda841d6d992c35dbbcc50fcee4aa86dfbbdeff7dc7e72c2305d5a62257f82737a8cffc80474c15c611c037f52db1a3a7b@[::]:21005",
  id: "eacaa74c4b0e7a9e12d2fe5fee6595eda841d6d992c35dbbcc50fcee4aa86dfbbdeff7dc7e72c2305d5a62257f82737a8cffc80474c15c611c037f52db1a3a7b",
  ip: "::",
  listenAddr: "[::]:21005",
  name: "Geth/v1.7.2-stable-ee498061/linux-amd64/go1.9.3",
  ports: {
    discovery: 21005,
    listener: 21005
  },
  protocols: {
    eth: {
      difficulty: 262144,
      genesis: "0xc23b4ebccc79e2636d66939924d46e618269ca1beac5cf1ec83cc862b88b1b71",
      head: "0x0fe371d5d3775fdd0bf32a56deade969b936ad35c7e91a5e1f1cb94bc7add1c8",
      network: 1
    }
  }
}
> eth.blockNumber
3
> var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"type":"constructor"}];
undefined
> var address = "0x9d13c6d3afe1721beef56b55d303b09e021e27ab";
undefined
> var private = eth.contract(abi).at(address);
undefined
> private.get();
42
>

**Comment by jpmsam** [comment]
Yes, that's expected. There is no direct link between the node and the associated keys. If the node has access to the keys, then it will be able to receive and decrypt the payloads.
