### ISSUE TITLE
Generating common key pairs for nodes (Constellation)

### ISSUE THREAD

**Issue by skarred14** [jpmorganchase/quorum-examples#82]
I have a generic question on the set up of constellation across quorum based nodes. i am trying to separate the transaction processing from mining - in the current set up, i have 2 containers each running a quorum image - one with rpc enabled and the other with miner enabled. is it possible to use the same key pairs for both such containers? in this case, would deploying contracts on the enclave work?

**Comment by jpmsam** [comment]
@skarred14 The contracts are deployed to Quorum, not constellation but you should be able to reuse the ethereum keys if you have shared the same private key between machines.
