### ISSUE TITLE
Quorum Stops Mining

### ISSUE THREAD

**Issue by HimanshuK18** [jpmorganchase/quorum-examples#83]
I have quorum 7 nodes example running on a ubuntu system, with RAFT consensus, it works all good till it reaches block number 2656 and after that it just stops mining or doing any contract updates. I am also facing the same issue on a second ubuntu server. Is there a bug in the latest code  ?

**Comment by jpmsam** [comment]
@HimanshuK18  This should be fixed with the most recent Quorum commit. Please let us know if you still experience this issue.
