### ISSUE TITLE
Using private.set() as described in the example returns an error when running under the istanbul configuration

### ISSUE THREAD

**Issue by bschapin** [jpmorganchase/quorum-examples#84]
Using private.set() as described in the example returns an error when running under the istanbul configuration. This code works running under the raft configuration.  

private.set(4,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
Error: unknown account
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:4137:16
    at apply (<native code>)
    at web3.js:4223:16
    at <anonymous>:1:1

**Comment by bschapin** [comment]
Syntax should be:

private.set(4,{from:web3.eth.accounts[0],privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});

**Comment by jpmsam** [comment]
Thanks for the update but eth.accounts[0] or eth.coinbase should work too if you are doing it from console.
