### ISSUE TITLE
7nodes node crashing - fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by drandreaskrueger** [jpmorganchase/quorum-examples#85]
# 7nodes node crashing - fatal error: runtime: out of memory

Playing with 7nodes example, testing `set` and `get` methods with `privateFor`

## Questions

- What is the correct way within the 7nodes example to *selectively start one crashed node*?
- What debug information can I give you, to solve the underlying issue that caused the crash described below?
- How can I increase the available RAM in that virtualmachine? I have 16 GB, so no problem.
- Is this a known problem? Are private transactions still very much beta perhaps?

## Problem Description

Suddenly my node1 disappeared - and reconnect fails:
```
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd1/geth.ipc
```
> Fatal: Unable to attach to remote geth: dial unix ~/quorum-examples/7nodes/qdata/dd1/geth.ipc: connect: no such file or directory

while the other nodes are still there:
```
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd7/geth.ipc
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd2/geth.ipc
etc.
```
all good.

Looking into the log files, I find this:
```
cat  ~/quorum-examples/7nodes/qdata/logs/1.log | grep mem
```

> fatal error: runtime: out of memory
>	/usr/local/go/src/runtime/mem_linux.go:216 +0x1d0

(same command for 2.log and 7.log ... result is empty instead --> no such memory problem)

# version 2.0.2
```
geth version
Geth
Version: 1.7.2-stable
Git Commit: ee498061b5a74bf1f3290139a53840345fa038cb
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
this ^ saying 2.0.1 is actually [wrong](https://github.com/jpmorganchase/quorum/issues/322), I had installed v2.0.2 from github release

**Comment by drandreaskrueger** [comment]
> How can I increase the available RAM in that virtualmachine?

Is this all I have to increase? https://github.com/jpmorganchase/quorum-examples/blob/master/Vagrantfile#L12




After starting from scratch again, and a couple of transactions, this is the status:

```
vagrant ssh

free -m
              total        used        free      shared  buff/cache   available
Mem:           2000        1314         528           3         157         525
Swap:             0           0           0
```

Anyone else had such memory problems, like described above?  What about creating 2048 MB swap by default, when initiating the vagrant-VM ?

Was it actually a memory problem, or might it have had other origins?  What debug information can I give you?

**Comment by jpmsam** [comment]
@drandreaskrueger I merged a PR in Quorum master that should improve memory allocation but you can increase the memory available in your vagrant config if needed.

**Comment by drandreaskrueger** [comment]
for now, working along [your suggestion 1.](https://github.com/jpmorganchase/quorum/issues/346#issuecomment-382216968), I am using

```
git checkout tags/v2.0.2
```

> I merged a PR in Quorum master that should improve memory allocation

@jpmsam give it a version tag?

**Comment by drandreaskrueger** [comment]
any news on a new [release](https://github.com/jpmorganchase/quorum/releases) ?
