### ISSUE TITLE
7nodes: some nodes with web3.eth.accounts==[ ]

### ISSUE THREAD

**Issue by drandreaskrueger** [jpmorganchase/quorum-examples#86]
Some of the nodes have no accounts created.

It would be useful if every node always gets initialized with one account, because that makes *testing private transactions* easier, e.g. in [Testing Privacy](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/README.md#testing-privacy) ... turning around the direction from node 7 to node 1.

Current situation:

### nodes 7, 6, 3
```
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd7/geth.ipc
web3.eth.accounts
```
> [ ]

### nodes 5, 4, 1
```
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd1/geth.ipc
web3.eth.accounts
```
> ["0x0638e..."]

### node 2
```
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd2/geth.ipc
web3.eth.accounts
```

> ["0xca8...", "0x0fbd..."]

#### quorum 2.0.2

```
geth version
Geth
Version: 1.7.2-stable
Git Commit: ee498061b5a74bf1f3290139a53840345fa038cb
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
quorum 2.0.2 not 2.0.1 = see https://github.com/jpmorganchase/quorum/issues/322

#### quorum-examples

```
git log
commit ee21fdb101bf82144f11d599efbfda0c3ec30c97
```

**Comment by drandreaskrueger** [comment]
easy to fix

    personal.newAccount("")

but why not already initialize all of the nodes with accounts?

**Comment by nlaz** [comment]
@drandreaskrueger This is why node 2 has two accounts and node 3 doesn't have any: https://github.com/jpmorganchase/quorum-examples/pull/88. Hopefully it gets reviewed and merged.

**Comment by jpmsam** [comment]
@drandreaskrueger @nlaz node 2 has two accounts as QuorumChain used one for voting and the other for sending transactions. Node 3 had no role in the consensus.  Since QuorumChain has been deprecated, i'll look merge PR [88](https://github.com/jpmorganchase/quorum-examples/pull/88)

**Comment by drandreaskrueger** [comment]
Thx a lot.

> i'll look merge PR #88 

Would that supply all 7 nodes with knowledge about each other?

In other words, when I grep for that public key:

     find . | xargs grep "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=" * 2>/dev/null

I find this folder

    ls ./examples/7nodes/keys/

which has 7 * 2 `*.key` (2 for each of the 7 nodes?), and 7 * 2 `*.pub` files

why two times?  (`tm[1-7].key` and `tm[1-7]a.key` and same for `*.pub`).

Plus 

*FIVE* more `key[1-5]` files.

Why 5 ?
Are those the 3+2 account keys for  nodes 5, 4, 1 and 2 ?

Is there a list of files in the 7nodes example, and their meanings?

Thanks a lot!

**Comment by drandreaskrueger** [comment]
Or ... to ask yet differently ... is 

    personal.newAccount("")

all I need to do to fix the lack of ability to be sending from nodes 7, 6, 3 - or do I have to do anything else?

Thanks!

**Comment by jpmsam** [comment]
@drandreaskrueger Creating a new account should do it.

**Comment by drandreaskrueger** [comment]
What speaks against making all nodes equivalent by default, e.g. making the lines in [raft-start.sh#L12-L18](https://github.com/jpmorganchase/quorum-examples/blob/8b6be8382477bfff29c2e9e4ea33c16fab674801/examples/7nodes/raft-start.sh#L12-L18) identical?

And giving each node an `eth.coinbase` account by default, etc.
