### ISSUE TITLE
7nodes: private.set(3) fails with a 500 Internal Server Error when done from node 7

### ISSUE THREAD

**Issue by drandreaskrueger** [jpmorganchase/quorum-examples#87]
`private.set(3)` fails with a `500 Internal Server Error` when done from node 7

### how to replicate:
```
vagrant up
vagrant ssh

cd quorum-examples/7nodes/
./raft-init.sh
./raft-start.sh
```

Then along the example ["Testing Privacy"](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/README.md#testing-privacy); i.e. node 1 deploys the contract, with `{"privateFor":"ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="}` visible for node 7, and not visible for node 2. 
```
./runscript.sh script1.js
```

Let's ignore node 2 for now ... 

... instead I want to **use node 7 as the origin** of newly set data:

```
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd7/geth.ipc 
```
from here onwards everything in that same JSRE console:
```
var address=web3.eth.getTransactionReceipt(web3.eth.getBlock(1).transactions[0])["contractAddress"]
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
var private = eth.contract(abi).at(address)
private.get()
```
because of https://github.com/jpmorganchase/quorum-examples/issues/86 -->
```
personal.newAccount("")
```

Here now I diverged from the example, trying out what happens 

* when I `set` data from node 2 (summary: node 2 can `set`, cannot `get`; and then node 1 still sees the old data, but node 7 sees the new data), 

* or when from node 7 = can `get` but ... 

# Problem:

... now when I do this on node 7:

```
private.set(3,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
```

this happens: 
```
Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 27 Mar 2018 15:38:21 GMT] Server:[Warp/3.2.13]] Body:0xc4285ce600 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc428eef900 TLS:<nil>}
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at web3.js:4137:16
    at apply (<native code>)
    at web3.js:4223:16
    at <anonymous>:1:1
```

If I understand the whole setup correctly, then node 7 owns the "ROAZBWtSa...", so that call does not make awfully much sense, admittedly. 

However, IMHO this attempt should not be crashing in such a rough way, no?

# Versions
same as in https://github.com/jpmorganchase/quorum-examples/issues/86

**Comment by nlaz** [comment]
Hey @drandreaskrueger I'm not a maintainer but I encountered this problem too. Transactions fail like that when the node's own key (ie. `ROAZBWtSa...`) is included in `privateFor`. 

So when running `private.set(...)` from node 7, make sure to avoid using node 7's key (`ROAZBWtSa...`). Instead, include the key for node 1 (`{ privateFor: ["BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="] }`) or no key at all `{ privateFor: [] }`. 

I agree with you though. It should have a helpful error response or should handle it's own key.

**Comment by drandreaskrueger** [comment]
Yes, I ran into Conor last week, and he explained this to me already.

Thanks a lot @nlaz - much appreciated. Will code around that hole.

To the maintainer:

Please you catch that understandable ("I encountered this problem too") wrong use of parameters, in your quorum code; and return a human readable error message - not a "500 Internal Server Error". Thanks a lot.

My boss asked me to evaluate whether quorum is worth looking at, and perhaps even ready to use; and stuff like this I have to mention.

**Comment by jpmsam** [comment]
Thanks @nlaz. @drandreaskrueger we'll be improving error messages and specifically for these type of common mistakes that we are seeing people encounter.

The privateFor list should only include the public keys for the other participants in the transaction.
