### ISSUE TITLE
Error while doing a private transaction

### ISSUE THREAD

**Issue by ksbachu** [jpmorganchase/quorum-examples#89]
Hi Team ,
We installed the 3 node raft basedsetup as per you steps. 
We an able to do public transactions and see the transactions hashes, block numbers.
But when we do the private transaction below error is coming. We struggled with multiple options and getting error for below transaction.

**`var Web3 = require('web3')
var web3 = new Web3(new Web3.providers.HttpProvider("RPC"))
a = web3.eth.accounts[0]
web3.eth.defaultAccount = a;
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"type":"constructor"}];
var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";

var simpleContract = web3.eth.contract(abi);
var simple = simpleContract.new(42, {from:web3.eth.accounts[0], data: bytecode, gas: 0x47b760, privateFor: ["utEnajeX+uUtV9OiyWi82SBUdNIiZBbTqQBJNNm80E8="]}, function(e, contract) {
	if (e) {
		console.log("err creating contract", e);
	} else {
		if (!contract.address) {
			console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
		} else {
			console.log("Contract mined! Address: " + contract.address);
			console.log(contract);
		}
	}
});`**

**Error**:
Error: Non-200 status code: &{Status:400 Bad Request StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Sun, 01 Apr 2018 12:27:40 GMT] Server:[Warp/3.2.12]] Body:0xc4256f6e80 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc425eccff0 TLS:}
at Object.InvalidResponse (/Users/sbachu/Documents/Demo/bcDemo/node_modules/web3/lib/web3/errors.js:38:16)
at /Users/sbachu/Documents/Demo/bcDemo/node_modules/web3/lib/web3/requestmanager.js:86:36
at XMLHttpRequest.request.onreadystatechange (/Users/sbachu/Documents/Demo/bcDemo/node_modules/web3/lib/web3/httpprovider.js:128:7)
at XMLHttpRequestEventTarget.dispatchEvent (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:64:18)
at XMLHttpRequest._setReadyState (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:354:12)
at XMLHttpRequest._onHttpResponseEnd (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:509:12)
at IncomingMessage. (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:469:24)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1056:12)

Please help us to move forward.

**Comment by jpmsam** [comment]
@krishnasaiiiit Please update to the most recent version and this should be fixed.
