### ISSUE TITLE
2 recipient keys in `privateFor` - not working???

### ISSUE THREAD

**Issue by drandreaskrueger** [jpmorganchase/quorum-examples#90]
This is really interesting stuff, thanks a lot. But I keep on running into new problems:

# several party `privateFor` = ???

## setup: 
start clean:
```
cd /opt/quorum/quorum-examples
vagrant destroy
vagrant up
vagrant status
```

start raft & deploy example contract
```
vagrant ssh

cd quorum-examples/7nodes
./raft-init.sh
./raft-start.sh

./runscript.sh script1.js
```

initialize several terminals, like this:

```
vagrant ssh
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd1/geth.ipc

var address=web3.eth.getTransactionReceipt(web3.eth.getBlock(1).transactions[0])["contractAddress"]
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
var private = eth.contract(abi).at(address)

private.get()
```
Let's call that ^ node 1 = "Alice".

Do the same 2 more times, for 2 more terminals:

"Bob" = node 7
```
vagrant ssh
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd7/geth.ipc
...
```
and

"Carol" = node 5
```
vagrant ssh
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd5/geth.ipc
...
```

#### My interpretation  - correct me if I am wrong please:
Initially, Alice and Bob can see the state (`42`) because Alice deployed the contract, and because Bob owns the `PrivateFor` PublicKey `ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=` that was used in `script1.js`

BUT Carol cannot see that state, instead she sees (`0`). 

All good, so far.

## extending visibility to 3 parties.

This is how I found Bob's key:

    find . | xargs grep "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=" * 2>/dev/null
    cat ./examples/7nodes/keys/tm7.pub

So I assume that Carol's key is this one:

    cat ./examples/7nodes/keys/tm5.pub

> R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=

Now use Alice's terminal (`geth attach ipc:.../dd1/geth.ipc` see above), to:

### `set(13)` from Alice (node 1)
I specify both Carol's and Bob's keys; and then do a `set` with those `privateFor` recipient keys:

```
PRIVATE_FOR=["R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=", "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]
tx=private.set(13,{from:eth.coinbase,privateFor:PRIVATE_FOR});
private.get()
```
> "0x2a3a0bd4e65a7b08e1d10fc5cb1cde8fc73ab28905cd2860250f6b598fec2a4b"  
> 13  

looks good. 

(If we accept the fact that Alice can see the data ... even though she neither owns `R56gy4dn2...` nor `ROAZBWtSa...` ... but she `set(13)` the new data, and she issued the contract in `script1.js` - which of these two reasons is the real reason actually?)

### `get()` from Bob (node 7)

```
private.get()
```
> 13

looks good.

### `get()` from Carol (node 5)

```
private.get()
```
> 0

Nope.

Something's wrong.

## Please replicate, and explain.
Please try out the above, and explain to me what I am doing wrong, or what is wrong in the  `7nodes` example.

Thanks a lot!

**Comment by jpmsam** [comment]
When you deploy the contract for the first time, you should update the privateFor fields in script1.js to include both keys:

PRIVATE_FOR=["R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=", "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]

When you run private.get() on node 5, since it never received a copy of the contract bytecode, you are get the default nil value, 0. You can confirm that by running eth.getCode(CONTRACT_ADDRESS) on both node 5 and node 7. Node 7 will have the bytecode but node 5 won't.

**Comment by drandreaskrueger** [comment]
> When you deploy the contract for the first time, 

Let's call that "strategy 1" - in some cases I might already know everyone whom I will share the data with.

> you should update the privateFor fields in script1.js to include both keys:

Thanks a lot. Will look into that when back in the office.


> When you run private.get() on node 5, 
> since it never received a copy of the contract bytecode, 
> you are get the default nil value, 0. 

Ah, now that explains it.  Thanks.
Where is the best place to read more about it the inner workings?


And ...


... what about strategy 2?

My example might be caused by having found out only later, that the data needs to be shared with Carol (node 5) too. 

What are the steps to make node 5 part of the secret group later, after the contract is already deployed?  

What do I have to do, to e.g. make node 5 "receive a copy of the contract bytecode"?
And what else?

**Comment by jpmsam** [comment]
@drandreaskrueger its not currently possible to add a new participant to an existing private contract. It's one of the enhancements that we have in our backlog.

**Comment by drandreaskrueger** [comment]
.

**Comment by drandreaskrueger** [comment]
Another thought ... for the *subset* of cases where the possible later viewers can be known ahead ... 

> When you deploy the contract for the first time, you should update the privateFor fields in script1.js to include both keys: [...]

might this workaround work then?

1. `A` deploys contract with `privateFor: [B, C]`  
2. `A` calls `set(13)` with `privateFor: [B]` - but not `C`   
3. `A` calls `set(get())` with `privateFor: [B,C]` 

(alternative *probably* identical result?:  --> 3. `B` calls `set(get())` with `privateFor: [A,C]`)

Consequences:

* C should not be able to see data after step 2 (???).
* C could perhaps not be sure that the data `13` at step 3. is the same it was at step 2. 

but 

* that way the data `13` could be temporarily hidden from some participants, until it is unlocked to them.

Correct thinking?

**Comment by drandreaskrueger** [comment]
Nothing beats running an experiment ;-)   


Start from scratch - approx 15 minutes to recreate VM  
(TODO: what would be a shortcut to destroy just the chain & anything related - but not the whole virtualbox?)

```
cd /opt/quorum/quorum-examples
vagrant destroy
```

```
vagrant up
vagrant status
vagrant ssh
```

```
cd quorum-examples/7nodes
./raft-init.sh
./raft-start.sh

cp script1.js script2.js 
sed -i.bak s/"ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="/"R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju\/1xkY=\",\"ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="/g script2.js 
cat script2.js 

./runscript.sh script2.js
```
now we have ^ a newly deployed contract in block 1 tx 1, which should have the correct access structure.


Get three terminals, for 

node 1 Alice 
```
vagrant ssh
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd1/geth.ipc 
```

node 7 Bob
```
vagrant ssh
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd7/geth.ipc 
```

node 5 Carol 
```
vagrant ssh
geth attach ipc:/home/vagrant/quorum-examples/7nodes/qdata/dd5/geth.ipc 
```

in *each* do the same:  
(TODO: this could become a `loadScript("init-private.js")` script, perhaps using always the latest block `eth.blockNumber` ?)
```
var address=web3.eth.getTransactionReceipt(web3.eth.getBlock(1).transactions[0])["contractAddress"]
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
var private = eth.contract(abi).at(address)

private.get()
```

answers should be:

42 Alice  
42 Bob  
42 Carol

**Comment by drandreaskrueger** [comment]
###### step 2.  Alice calls `set(13)` with `privateFor: [Bob]` - but not `Carol`

`set` from Alice (node 1)
```
private.set(13,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
```
wait a moment, until the block is sealed.

`get()` from Alice and Bob and Carol:
```
private.get()
```

answers should be:

13 Alice  
13 Bob  
42 Carol

**Comment by drandreaskrueger** [comment]
###### step 3.  Alice calls `set(get())` with `privateFor: [Bob, Carol]`

`set(get())` from Alice (node 1)
```
BOBnCAROL=["R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=", "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]
private.set(private.get(),{from:eth.coinbase, privateFor:BOBnCAROL});
```
wait a moment, until the block is sealed.

`get()` from Alice and Bob and Carol:
```
private.get()
```

answers should be:

13 Alice  
13 Bob  
13 Carol  


Hooray. Workaround ... works.

N.B.: Only if possible later collaborateurs are known initially already (when contract is deployed).

**Comment by drandreaskrueger** [comment]
I have made this into files now:

* [init-private.js](https://github.com/drandreaskrueger/quorum-examples/blob/master/examples/7nodes/init-private.js)
* [script2.js](https://github.com/drandreaskrueger/quorum-examples/blob/master/examples/7nodes/script2.js)
* [revealing-later.md](https://github.com/drandreaskrueger/quorum-examples/blob/master/examples/7nodes/revealing-later.md)

and into a [pull request #93](https://github.com/jpmorganchase/quorum-examples/pull/93)

**Comment by drandreaskrueger** [comment]
> @drandreaskrueger its not currently possible to add a new participant to an existing private contract. It's one of the enhancements that we have in our backlog.

Thanks @jpmsam - That is important for us to know.  

I suggest you document that fact somewhere.  

Where can I see the backlog, and possibly priorities?

And: Do you have an intuition for a solution already? Will that enhancement be very hard to implement - or is it just some rather simple additional code to be written?

**Comment by jpmsam** [comment]
@drandreaskrueger we have a design but it will take bit longer to implement. We'll be updating the wiki with this FAQ.

CC @tylobban
