### ISSUE TITLE
Instruction at start.sh

### ISSUE THREAD

**Issue by tsuzukit** [jpmorganchase/quorum-examples#92]
Hi

I'm new to Quorum and wonder if instruction shown is slightly wrong.

When I finishes running `raft-start.sh` , I see

```
To test sending a private transaction from Node 1 to Node 7, run './runscript script1.js'
```

Shouldn't this be below?

```
To test sending a private transaction from Node 1 to Node 7, run './runscript.sh script1.js'
```

I know this is really subtle issue and please close issue if this is irrelevant here.

**Comment by jpmsam** [comment]
@tsuzukit thanks, fixed.
