### ISSUE TITLE
ubuntu vs. vagrant

### ISSUE THREAD

**Issue by kctam** [jpmorganchase/quorum-examples#96]
I have just cloned the latest code and when vagrant up, i found an error showing that /home/vagrant/.bashrc doesn't exist. When I vagrant ssh into the VM it seems the directory is /home/ubuntu instead of /home/vagrant. I also double check a setup back last July and it seems it was /home/ubuntu instead of /home/vagrant in bootstrap.sh.

After I modify the bootstrap.sh with /home/ubuntu things work perfectly.

Thanks.

**Comment by kctam** [comment]
Seems it's the same issue of #65. However mine is the way around. So I suppose it's the issue from vagrant, but seems both scenarios occur. It's better to make a note to all about this.

**Comment by jpmsam** [comment]
@kctam You have an old local copy of the vagrant ubuntu box. Please refer to vagrant's [command line](https://www.vagrantup.com/docs/cli/box.html#box-remove) for the details on how to remove it, it should be `vagrant box remove` with the name of the box. Once you remove the local version, you can start over and it should work.
